<a href="https://colab.research.google.com/github/JuniorDurand/P-Median-Problem/blob/main/P_medianas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Problema das P-medianas

## Ambiente

In [1]:
import os
import numpy as np
import itertools
from itertools import combinations
from random import randint
import datetime
import heapq

## Dataset

### Synthetic Dataset

In [ ]:
vertices = [10, 20, 50, 70, 100, 150, 200]
ps = [2, 5, 10]
count = 1

for p in ps:
  for v in vertices:

    if p >= v:
      continue

    if os.path.isfile("syntpmed{count}.txt".format(count=count)):
      count = count + 1
      continue

    arq = open("syntpmed{count}.txt".format(count=count), "a")

    # head of file
    arq.write("{v} {p}\n".format(v=v, p=p))
    for i in combinations(range(v), 2):

      # define rand cost
      c = randint(0,100)
      # writer edge line
      arq.write("{i} {j} {c}\n".format(i=i[0]+1, j=i[1]+1, c=c))

    arq.close()
    count = count + 1




### Brunel Dataset

[Brunel Dataset](http://people.brunel.ac.uk/~mastjjb/jeb/orlib/pmedinfo.html)

In [2]:
brunel_pmeds = [
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed1.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed2.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed3.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed4.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed5.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed6.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed7.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed8.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed9.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed10.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed11.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed12.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed13.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed14.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed15.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed16.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed17.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed18.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed19.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed20.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed21.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed22.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed23.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed24.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed25.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed26.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed27.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed28.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed29.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed30.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed31.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed32.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed33.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed34.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed35.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed36.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed37.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed38.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed39.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed40.txt",
]

In [3]:
for pmed in brunel_pmeds
  os.system('wget {FILE}'.format(FILE = pmed))

0

In [4]:
def get_dataset(filepath):
  with open(filepath.split('/')[-1]) as f:
    content = f.readlines()

  params = content[0].split()
  params = [int(x) for x in params]

  # def dataset parans
  vertices = params[0]
  edges = params[1]
  p = params[2]

  # preprocess cost edges
  cost = [x.split() for x in content[1:]]
  cost = [list(map(int, x)) for x in cost]

  # create mat cost
  cost_mat = np.full((vertices, vertices), np.nan)
  for i, j, c in cost:
    cost_mat[i-1][j-1] = c
    cost_mat[j-1][i-1] = c

  for i in range(vertices):
    cost_mat[i][i] = 0

  return {
      "vertices" : vertices,
      "edges": edges,
      "p": p,
      "cost_mat": cost_mat
  }


## Solução Linear

###Funções Utilitarias

In [ ]:
class BinaryCount:
  def __init__(self, length: int, start: int = 0):
    self.length = length
    self.start = start
    self.i = self.start

  def __get_zeros(self, n):
    zeros = ""
    for i in range(n):
      zeros = zeros + str(0)

    return zeros

  def __string_to_list_int(self, string):
    bin_list = [*string]
    bin_list = [ int(x) for x in bin_list]
    return bin_list

  def __next__(self):
    bin_code = "{number:b}".format(number=self.i)
    self.i = self.i + 1

    if(len(bin_code) < self.length):
      bin_code = self.__get_zeros(self.length - len(bin_code)) + bin_code

    elif (len(bin_code) == self.length):
      bin_code = bin_code

    else:
      raise StopIteration

    # return bin_code
    return self.__string_to_list_int(bin_code)

  def __iter__(self):
    return self


In [ ]:
# bin_count = BinaryCount(2  * (2+1))

# for i in bin_count:
#   sol = np.array(i)
#   sol = np.reshape(sol, (2, (2 + 1)))
#   print(sol)

In [ ]:
def get_cost_sol(vertices, sol, cost_mat):
  total_cost = 0
  for i in range(vertices):
    for j in range(vertices):
      if not np.isnan(cost_mat[i][j]):
        total_cost = total_cost + (cost_mat[i][j] * sol[i][j])
      elif( sol[i][j] > 0):
        raise Exception
      else:
        continue;
  return total_cost



In [ ]:
cost = [[10,10,10], [10,10,10], [10,10,np.nan]]

sol = [[0,1,1], [1,0,0], [1,0,0]]

print(get_cost_sol(3, sol, cost))
# for i in range(3):
#   for j in range(i, 3):
#     print(mat[i][j])

20


In [ ]:
def restriction_all_served(vertices, sol):
  sol = np.array(sol)
  for i in range(vertices):
    col = sol[:, i]
    sum = np.sum(col)
    if(sum != 1):
      return False
  return True

sol_test = [[0,1,0], [1,0,0], [0,0,0]]
restriction_all_served(3, sol_test)

False

In [ ]:
def restriction_p_servers(vertices, p, sol):
  sol = np.array(sol)

  col = sol[:, vertices]
  sum = np.sum(col)
  if(sum != p):
    return False
  return True

sol_test = [[0,1,0,0], [1,0,0,1], [0,0,0,0]]
restriction_p_servers(3, 2, sol_test)

False

In [ ]:
def restriction_served_by_open_servers(vertices, sol):
  sol = np.array(sol)

  for i in range(vertices):
    row = sol[i, :vertices]
    for j in row:
      if not(j - sol[i,vertices] <= 0):
        # print(i, row, sol[i,vertices])
        return False
  return True

sol_test = [[0,1,0,1], [1,0,0,1], [0,0,0,1]]
restriction_served_by_open_servers(3, sol_test)

True

### Solução

In [ ]:
def linear_solver(vertices, edges, p, cost_mat):
  solutions = []

  bin_count = BinaryCount( vertices * (vertices + 1) )

  for bin in bin_count:
    sol = np.array(bin)
    sol = np.reshape(sol, (vertices, (vertices + 1)))


    if not restriction_p_servers(vertices, p, sol):
      continue;

    if not restriction_all_served(vertices, sol):
      continue;

    if not restriction_served_by_open_servers(vertices, sol):
      continue;
    # print(sol)

    cost = get_cost_sol(vertices, sol, cost_mat)

    solutions.append([cost, sol])

  return solutions








In [ ]:
data = get_dataset('./pmed00.txt')

print(data)

solutions = linear_solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])

solutions.sort(key=lambda s : s[0])

for s in solutions:
  print(s[0])
  print(s[1])

{'vertices': 4, 'edges': 40, 'p': 2, 'cost_mat': array([[ 0., 34., 32., 66.],
       [34.,  0., 73., 63.],
       [32., 73.,  0., 92.],
       [66., 63., 92.,  0.]])}
66.0
[[1 1 1 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 1]]
95.0
[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 1 0 1]
 [0 1 0 1 1]]
95.0
[[0 0 0 0 0]
 [0 1 0 1 1]
 [1 0 1 0 1]
 [0 0 0 0 0]]
95.0
[[1 0 1 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 1 1]]
95.0
[[1 0 1 0 1]
 [0 1 0 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]
97.0
[[0 0 0 0 0]
 [1 1 0 1 1]
 [0 0 1 0 1]
 [0 0 0 0 0]]
98.0
[[1 0 1 1 1]
 [0 1 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]
100.0
[[1 1 0 1 1]
 [0 0 0 0 0]
 [0 0 1 0 1]
 [0 0 0 0 0]]
105.0
[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 0 1]
 [0 0 0 1 1]]
107.0
[[0 0 0 0 0]
 [1 1 1 0 1]
 [0 0 0 0 0]
 [0 0 0 1 1]]
124.0
[[0 0 0 0 0]
 [0 1 0 0 1]
 [1 0 1 1 1]
 [0 0 0 0 0]]
126.0
[[0 0 0 0 0]
 [1 1 0 0 1]
 [0 0 0 0 0]
 [0 0 1 1 1]]
126.0
[[0 0 0 0 0]
 [1 1 0 0 1]
 [0 0 1 1 1]
 [0 0 0 0 0]]
126.0
[[1 1 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 1 1]]
126.0
[[1 1 0 

### Def Simple Test

In [ ]:
arquivo = open("pmed00.txt", "a")
v = 4
a  = 40
p = 2

arquivo.write("{v} {a} {p}\n".format(v=v, p=p, a=a))
for i in combinations(range(v), 2):
  c = randint(0,100)
  arquivo.write("{i} {j} {c}\n".format(i=i[0]+1, j=i[1]+1, c=c))

arquivo.close()

## Solução não Linear

### Funções Utilitarias

### Clase Solução

In [5]:
class Solution:
  def __init__(self, vertices: int, p: list, c_mat):
    self.v = vertices
    self.p = p
    self.c_mat = c_mat
    # self.s_mat = np.full((vertices, vertices), 0, dtype=int)
    self.s_vet = []

    # col iterator
    self.i = 0

    # solution cost
    self.c = 0.0

    # possible solution
    self.impossible = False

    self.nancount = 0

  # exec sol step
  def sol_step(self):
    if self.i < self.v:
      min_cost_serv = float("inf")
      min_cost_serv_ind = None
      for serv in self.p:

        # if cost not def continue
        if np.isnan(self.c_mat[serv][self.i]):
          continue

        # update cost min
        if self.c_mat[serv][self.i] < min_cost_serv:
          min_cost_serv = self.c_mat[serv][self.i]
          min_cost_serv_ind = serv

      # if not find edge sol, is impossible
      if min_cost_serv_ind is None :
        # self.impossible = True;
        # self.c = float("inf")
        # self.i = self.v
        self.s_vet.append(np.nan)
        self.i = self.i + 1
        self.c = self.c + 0
        self.nancount = self.nancount + 1

      # update solution
      else:
        # add sol into s_mat
        # self.s_mat[min_cost_serv_ind][self.i] = 1
        self.s_vet.append(min_cost_serv_ind)
        # iterate col
        self.i = self.i + 1
        # update cost
        self.c = self.c + min_cost_serv

  def solved(self):
    if self.i < self.v:
      return False
    else:
      return True

  def __lt__(self, s):
    return self.c < s.c

  def __le__(self, s):
    return self.c <= s.c

  def __eq__(self, s):
    return self.c == s.c

  def __gt__(self, s):
    return self.c > s.c

  def __ge__(self, s):
    return self.c >= s.c



### Solver

In [6]:
def solver(vertices, edges, p, cost_mat):
  solutions = []

  # create solutions instances
  comb = combinations(range(vertices), p)
  for c in list(comb):
    s = Solution(vertices, c, cost_mat)
    solutions.append(s)

  # resolve all solutions
  for s in solutions:
    while not s.solved():
      s.sol_step()
  return solutions








### Executa Solução

In [ ]:
data = get_dataset('./pmed1.txt')

print(data)

# ct stores current time
ct = datetime.datetime.now()
print("Start time:-", ct)
ts = ct.timestamp()
print("timestamp:-", ts)

solutions = solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])

# ct stores current time
ct = datetime.datetime.now()
print("End time:-", ct)
ts = ct.timestamp()
print("timestamp:-", ts)

solutions.sort()

print(solutions[0].c)
print(solutions[0].s_vet)

# for s in solutions:
#   if not s.impossible:
#     print(s.c)
#     print(s.s_vet)

{'vertices': 100, 'edges': 200, 'p': 5, 'cost_mat': array([[ 0., 30., nan, ..., nan, nan, 88.],
       [30.,  0., 46., ..., nan, nan, nan],
       [nan, 46.,  0., ..., nan, 49., nan],
       ...,
       [nan, nan, nan, ...,  0., 31., nan],
       [nan, nan, 49., ..., 31.,  0., 49.],
       [88., nan, nan, ..., nan, 49.,  0.]])}
Start time:- 2023-07-10 13:44:18.939816
timestamp:- 1688996658.939816


In [17]:
# print(solutions[0].c)
# print(solutions[0].s_vet)
# print(solutions[0].impossible)

max = 0
for s in solutions:
  # if not s.impossible:
  # print(s.c)
  if len(s.s_vet) > max:
    max = len(s.s_vet)
    print(s.s_vet)
    print(s.p)
    # break
print(max)

[0, 1, 2, 3, 4, 4, 4]
(0, 1, 2, 3, 4)
[0, 1, 2, 3, 6, 6, 6, 6]
(0, 1, 2, 3, 6)
[0, 1, 2, 2, 4, 4, 4, 7, 7]
(0, 1, 2, 4, 7)
[0, 1, 2, 2, 4, 4, 4, 8, 8, 8]
(0, 1, 2, 4, 8)
[0, 1, 2, 2, 6, 6, 6, 6, 9, 9, 9]
(0, 1, 2, 6, 9)
[0, 1, 1, 4, 4, 4, 4, 7, 7, 10, 10, 10, 7]
(0, 1, 4, 7, 10)
[0, 1, 1, 4, 4, 4, 4, 12, 9, 9, 9, 12, 12, 12]
(0, 1, 4, 9, 12)
[1, 1, 1, 4, 4, 4, 4, 7, 7, 10, 10, 10, 13, 13, 13]
(1, 4, 7, 10, 13)
[1, 1, 1, 4, 4, 4, 4, 7, 7, 10, 10, 10, 7, 14, 14, 14]
(1, 4, 7, 10, 14)
[1, 1, 1, 4, 4, 4, 4, 12, 9, 9, 9, 12, 12, 12, 15, 15, 15]
(1, 4, 9, 12, 15)
17


In [ ]:
def solver_test(vertices, edges, p, cost_mat):
  solutions = []

  # create solutions instances
  comb = combinations(range(vertices), p)
  print(len(list(comb)))
  # for c in list(comb):
  #   s = Solution(vertices, c, cost_mat)
  #   solutions.append(s)

  # # resolve all solutions
  # for s in solutions:
  #   while not s.solved():
  #     s.sol_step()
  # return solutions

In [ ]:
solutions = solver_test(data["vertices"], data["edges"], data["p"], data["cost_mat"])


75287520


## Solução não Linear com Heuristica

### Funções Utilitarias

### Solver

In [ ]:
def heuristic_solver(vertices, edges, p, cost_mat):
  solutions = []

  # create solutions instances
  comb = combinations(range(vertices), p)
  for c in list(comb):
    s = Solution(vertices, c, cost_mat)
    solutions.append(s)

  # get first of priority queue
  s = solutions[0]
  while not s.solved() and not s.impossible:

    # sol step first of heap
    s.sol_step()

    if s.impossible:
      heapq.heappop(solutions)

    # heapify heap
    heapq.heapify(solutions)
    # get most promising solution
    s = solutions[0]

  return solutions





In [ ]:
data = get_dataset('./pmed1.txt')

print(data)

# ct stores current time
ct = datetime.datetime.now()
print("Start time:-", ct)
ts = ct.timestamp()
print("timestamp:-", ts)

solutions = heuristic_solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])

# ct stores current time
ct = datetime.datetime.now()
print("End time:-", ct)
ts = ct.timestamp()
print("timestamp:-", ts)

solutions.sort()

print(s[0].c)
print(s[0].s_vet)

# for s in solutions:
#   if not s.impossible:
#     print(s.c)
#     print(s.s_vet)

{'vertices': 100, 'edges': 200, 'p': 5, 'cost_mat': array([[ 0., 30., nan, ..., nan, nan, 88.],
       [30.,  0., 46., ..., nan, nan, nan],
       [nan, 46.,  0., ..., nan, 49., nan],
       ...,
       [nan, nan, nan, ...,  0., 31., nan],
       [nan, nan, 49., ..., 31.,  0., 49.],
       [88., nan, nan, ..., nan, 49.,  0.]])}
Start time:- 2023-07-10 12:32:44.243576
timestamp:- 1688992364.243576


In [ ]:
def solver_test(vertices, edges, p, cost_mat):
  solutions = []

  # create solutions instances
  comb = combinations(range(vertices), p)
  print(len(list(comb)))
  # for c in list(comb):
  #   s = Solution(vertices, c, cost_mat)
  #   solutions.append(s)

  # # resolve all solutions
  # for s in solutions:
  #   while not s.solved():
  #     s.sol_step()
  # return solutions

In [ ]:
solutions = solver_test(data["vertices"], data["edges"], data["p"], data["cost_mat"])


75287520
