<a href="https://colab.research.google.com/github/JuniorDurand/P-Median-Problem/blob/main/P_medianas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Problema das P-medianas

## Environment

In [1]:
import os
import numpy as np
import itertools
from itertools import combinations
from random import randint
import datetime
import heapq
import pandas as pd
import random

In [2]:
!git clone https://github.com/JuniorDurand/P-Median-Problem.git

os.chdir("P-Median-Problem")

Cloning into 'P-Median-Problem'...
remote: Enumerating objects: 67, done.
remote: Total 67 (delta 0), reused 0 (delta 0), pack-reused 67
Unpacking objects: 100% (67/67), 602.51 KiB | 2.57 MiB/s, done.


## Dataset

### Synthetic Dataset

In [ ]:
vertices = [10, 20, 50, 70, 100, 150, 200]
ps = [2, 5, 10, 15]
count = 1
synthetic_pmeds = []

for p in ps:
  for v in vertices:

    if p >= v:
      continue

    file_path = "syntpmed{count}.txt".format(count=count)

    if os.path.isfile(file_path):
      count = count + 1
      synthetic_pmeds.append(file_path)
      continue

    arq = open(file_path, "a")

    # head of file
    arq.write("{v} {p}\n".format(v=v, p=p))
    for i in combinations(range(v), 2):

      # define rand cost
      c = randint(0,100)
      # writer edge line
      arq.write("{i} {j} {c}\n".format(i=i[0]+1, j=i[1]+1, c=c))

    arq.close()
    count = count + 1
    synthetic_pmeds.append(file_path)




### Brunel Dataset

[Brunel Dataset](http://people.brunel.ac.uk/~mastjjb/jeb/orlib/pmedinfo.html)

The graphs resulting from this dataset are not complete so they were not used in the analysis

In [ ]:
brunel_pmeds = [
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed1.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed2.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed3.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed4.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed5.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed6.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed7.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed8.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed9.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed10.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed11.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed12.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed13.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed14.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed15.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed16.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed17.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed18.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed19.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed20.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed21.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed22.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed23.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed24.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed25.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed26.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed27.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed28.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed29.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed30.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed31.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed32.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed33.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed34.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed35.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed36.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed37.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed38.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed39.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed40.txt",
]

In [ ]:
for pmed in brunel_pmeds:
  os.system('wget {FILE}'.format(FILE = pmed))

###Utility Functions

In [ ]:
def get_dataset(filepath):
  with open(filepath.split('/')[-1]) as f:
    content = f.readlines()

  params = content[0].split()
  params = [int(x) for x in params]

  # def dataset parans
  vertices = params[0]
  p = params[1]
  edges = 0

  # preprocess cost edges
  cost = [x.split() for x in content[1:]]
  cost = [list(map(int, x)) for x in cost]

  # create mat cost
  cost_mat = np.full((vertices, vertices), np.nan)
  for i, j, c in cost:
    cost_mat[i-1][j-1] = c
    cost_mat[j-1][i-1] = c

  for i in range(vertices):
    cost_mat[i][i] = 0

  return {
      "vertices" : vertices,
      "edges": edges,
      "p": p,
      "cost_mat": cost_mat
  }


## Linear Solution

###Utility Functions

#### Binary count

In [ ]:
class BinaryCount:
  def __init__(self, length: int, start: int = 0):
    self.length = length
    self.start = start
    self.i = self.start

  def __get_zeros(self, n):
    zeros = ""
    for i in range(n):
      zeros = zeros + str(0)

    return zeros

  def __string_to_list_int(self, string):
    bin_list = [*string]
    bin_list = [ int(x) for x in bin_list]
    return bin_list

  def __next__(self):
    bin_code = "{number:b}".format(number=self.i)
    self.i = self.i + 1

    if(len(bin_code) < self.length):
      bin_code = self.__get_zeros(self.length - len(bin_code)) + bin_code

    elif (len(bin_code) == self.length):
      bin_code = bin_code

    else:
      raise StopIteration

    # return bin_code
    return self.__string_to_list_int(bin_code)

  def __iter__(self):
    return self


#### Get cost of solution

In [ ]:
def get_cost_sol(vertices, sol, cost_mat):
  total_cost = 0
  for i in range(vertices):
    for j in range(vertices):
      if not np.isnan(cost_mat[i][j]):
        total_cost = total_cost + (cost_mat[i][j] * sol[i][j])
      elif( sol[i][j] > 0):
        raise Exception
      else:
        continue;
  return total_cost



#### Check all served vertices restriction

In [ ]:
def restriction_all_served(vertices, sol):
  sol = np.array(sol)
  for i in range(vertices):
    col = sol[:, i]
    sum = np.sum(col)
    if(sum != 1):
      return False
  return True

sol_test = [[0,1,0], [1,0,0], [0,0,0]]
restriction_all_served(3, sol_test)

False

#### Check number of servers restriction

In [ ]:
def restriction_p_servers(vertices, p, sol):
  sol = np.array(sol)

  col = sol[:, vertices]
  sum = np.sum(col)
  if(sum != p):
    return False
  return True

sol_test = [[0,1,0,0], [1,0,0,1], [0,0,0,0]]
restriction_p_servers(3, 2, sol_test)

False

#### Check vertives served by open servers

In [ ]:
def restriction_served_by_open_servers(vertices, sol):
  sol = np.array(sol)

  for i in range(vertices):
    row = sol[i, :vertices]
    for j in row:
      if not(j - sol[i,vertices] <= 0):
        # print(i, row, sol[i,vertices])
        return False
  return True

sol_test = [[0,1,0,1], [1,0,0,1], [0,0,0,1]]
restriction_served_by_open_servers(3, sol_test)

True

### Solver

In [ ]:
def linear_solver(vertices, edges, p, cost_mat):
  solutions = []

  bin_count = BinaryCount( vertices * (vertices + 1) )

  for bin in bin_count:
    sol = np.array(bin)
    sol = np.reshape(sol, (vertices, (vertices + 1)))


    if not restriction_p_servers(vertices, p, sol):
      continue;

    if not restriction_all_served(vertices, sol):
      continue;

    if not restriction_served_by_open_servers(vertices, sol):
      continue;
    # print(sol)

    cost = get_cost_sol(vertices, sol, cost_mat)

    solutions.append([cost, sol])

  return solutions








### Execute Solution

In [ ]:
data = get_dataset('./pmed00.txt')

print(data)

solutions = linear_solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])

solutions.sort(key=lambda s : s[0])


print("Best cost: ", solutions[0][0])
print("Best solution matrix: \n", solutions[0][1])

{'vertices': 4, 'edges': 40, 'p': 2, 'cost_mat': array([[ 0., 34., 32., 66.],
       [34.,  0., 73., 63.],
       [32., 73.,  0., 92.],
       [66., 63., 92.,  0.]])}
66.0
[[1 1 1 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 1]]
95.0
[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 1 0 1]
 [0 1 0 1 1]]
95.0
[[0 0 0 0 0]
 [0 1 0 1 1]
 [1 0 1 0 1]
 [0 0 0 0 0]]
95.0
[[1 0 1 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 1 1]]
95.0
[[1 0 1 0 1]
 [0 1 0 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]
97.0
[[0 0 0 0 0]
 [1 1 0 1 1]
 [0 0 1 0 1]
 [0 0 0 0 0]]
98.0
[[1 0 1 1 1]
 [0 1 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]
100.0
[[1 1 0 1 1]
 [0 0 0 0 0]
 [0 0 1 0 1]
 [0 0 0 0 0]]
105.0
[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 0 1]
 [0 0 0 1 1]]
107.0
[[0 0 0 0 0]
 [1 1 1 0 1]
 [0 0 0 0 0]
 [0 0 0 1 1]]
124.0
[[0 0 0 0 0]
 [0 1 0 0 1]
 [1 0 1 1 1]
 [0 0 0 0 0]]
126.0
[[0 0 0 0 0]
 [1 1 0 0 1]
 [0 0 0 0 0]
 [0 0 1 1 1]]
126.0
[[0 0 0 0 0]
 [1 1 0 0 1]
 [0 0 1 1 1]
 [0 0 0 0 0]]
126.0
[[1 1 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 1 1]]
126.0
[[1 1 0 

## Improved Linear Solution

### Class Solution

In [ ]:
class Solution:
  def __init__(self, vertices: int, p: list, c_mat):
    self.v = vertices
    self.p = p
    self.c_mat = c_mat
    # self.s_mat = np.full((vertices, vertices), 0, dtype=int)
    self.s_vet = []

    # col iterator
    self.i = 0

    # solution cost
    self.c = 0.0

    # possible solution
    self.impossible = False

    self.nancount = 0

  # exec sol step
  def sol_step(self):
    if self.i < self.v:
      min_cost_serv = float("inf")
      min_cost_serv_ind = None
      for serv in self.p:

        # if cost not def continue
        if np.isnan(self.c_mat[serv][self.i]):
          continue

        # update cost min
        if self.c_mat[serv][self.i] < min_cost_serv:
          min_cost_serv = self.c_mat[serv][self.i]
          min_cost_serv_ind = serv

      # if not find edge sol, is impossible
      if min_cost_serv_ind is None :
        self.impossible = True;
        self.c = float("inf")
        self.i = self.v

      # update solution
      else:
        # add sol into v_mat
        self.s_vet.append(min_cost_serv_ind)
        # iterate col
        self.i = self.i + 1
        # update cost
        self.c = self.c + min_cost_serv

  def solved(self):
    if self.i < self.v:
      return False
    else:
      return True

  def __lt__(self, s):
    return self.c < s.c

  def __le__(self, s):
    return self.c <= s.c

  def __eq__(self, s):
    return self.c == s.c

  def __gt__(self, s):
    return self.c > s.c

  def __ge__(self, s):
    return self.c >= s.c



### Solver

In [ ]:
def solver(vertices, edges, p, cost_mat):
  solutions = []

  # create solutions instances
  comb = combinations(range(vertices), p)
  for c in list(comb):
    s = Solution(vertices, c, cost_mat)
    solutions.append(s)

  # resolve all solutions
  for s in solutions:
    while not s.solved():
      s.sol_step()
  return solutions








### Execute Solution

In [ ]:
h = []

for pmed in synthetic_pmeds:
  data = get_dataset(pmed)

  start_time =  datetime.datetime.now()
  solutions = solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])
  end_time =  datetime.datetime.now()

  solutions.sort()

  h.append({
      "file": pmed,
      "start_time": start_time,
      "end_time": end_time,
      "min_cost": solutions[0].c,
      "s_vet": solutions[0].s_vet
  })
  print(h)

print(h)

[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 10, 15, 44, 29, 317428), 'end_time': datetime.datetime(2023, 7, 10, 15, 44, 29, 320055), 'min_cost': 153.0, 's_vet': [0, 3, 3, 3, 0, 3, 3, 3, 0, 3]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 10, 15, 44, 29, 317428), 'end_time': datetime.datetime(2023, 7, 10, 15, 44, 29, 320055), 'min_cost': 153.0, 's_vet': [0, 3, 3, 3, 0, 3, 3, 3, 0, 3]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 10, 15, 44, 29, 321443), 'end_time': datetime.datetime(2023, 7, 10, 15, 44, 29, 350523), 'min_cost': 349.0, 's_vet': [19, 11, 19, 11, 19, 11, 11, 11, 19, 19, 11, 11, 11, 19, 11, 19, 19, 11, 19, 19]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 10, 15, 44, 29, 317428), 'end_time': datetime.datetime(2023, 7, 10, 15, 44, 29, 320055), 'min_cost': 153.0, 's_vet': [0, 3, 3, 3, 0, 3, 3, 3, 0, 3]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 10, 15, 44, 

In [ ]:
h_df = pd.DataFrame(h)
print(h_df)
h_df.to_csv("linear_sol.csv")

## Linear Solution with Heuristics

### Solver

In [ ]:
def heuristic_solver(vertices, edges, p, cost_mat):
  solutions = []

  # create solutions instances
  comb = combinations(range(vertices), p)
  for c in list(comb):
    s = Solution(vertices, c, cost_mat)
    solutions.append(s)

  # get first of priority queue
  s = solutions[0]
  while not s.solved() and not s.impossible:

    # sol step first of heap
    s.sol_step()

    if s.impossible:
      heapq.heappop(solutions)

    # heapify heap
    heapq.heapify(solutions)
    # get most promising solution
    s = solutions[0]

  return solutions

In [ ]:
h = []

for pmed in synthetic_pmeds:
  data = get_dataset(pmed)

  start_time =  datetime.datetime.now()
  solutions = heuristic_solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])
  end_time =  datetime.datetime.now()

  solutions.sort()

  h.append({
      "file": pmed,
      "start_time": start_time,
      "end_time": end_time,
      "min_cost": solutions[0].c,
      "s_vet": solutions[0].s_vet
  })
  print(h)

print(h)

In [ ]:
h_df = pd.DataFrame(h)
print(h_df)
h_df.to_csv("heuristic_old_sol.csv")

## Myopic Solution

### Solver

In [ ]:
def heuristic_myopic_solver(vertices, edges, p, cost_mat):
  # solutions = []

  # create solutions instances
  solution_candidate = []
  s = None
  while len(solution_candidate) < p:
    s_list = solution_candidate.copy()
    s_list_temp = solution_candidate.copy()
    s_list_temp.append(-1)
    s_cost = float("inf")
    s_temp = None

    for i in range(vertices):
      if i not in s_list:
        s_list_temp[len(solution_candidate)] = i
        s_temp = Solution(vertices, s_list_temp, cost_mat)

        while not s_temp.solved():
          s_temp.sol_step()

        if s_cost > s_temp.c:
          # print(s_temp.c)
          s_list = s_list_temp
          s_cost = s_temp.c
          s = s_temp

    solution_candidate = s_list
  return s, solution_candidate

In [ ]:
h = []

for pmed in synthetic_pmeds:
  data = get_dataset(pmed)

  start_time =  datetime.datetime.now()
  solutions = heuristic_myopic_solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])
  end_time =  datetime.datetime.now()

  # solutions.sort()

  h.append({
      "file": pmed,
      "start_time": start_time,
      "end_time": end_time,
      "min_cost": solutions[0].c,
      "s_vet": solutions[0].s_vet
  })
  print(h)

print(h)

[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 37, 49, 540791), 'end_time': datetime.datetime(2023, 7, 11, 13, 37, 49, 541816), 'min_cost': 186.0, 's_vet': [5, 5, 5, 5, 5, 5, 5, 9, 5, 9]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 37, 49, 540791), 'end_time': datetime.datetime(2023, 7, 11, 13, 37, 49, 541816), 'min_cost': 186.0, 's_vet': [5, 5, 5, 5, 5, 5, 5, 9, 5, 9]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 37, 49, 543621), 'end_time': datetime.datetime(2023, 7, 11, 13, 37, 49, 547756), 'min_cost': 372.0, 's_vet': [19, 9, 9, 9, 9, 9, 19, 19, 9, 9, 19, 19, 19, 19, 19, 9, 19, 19, 9, 19]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 37, 49, 540791), 'end_time': datetime.datetime(2023, 7, 11, 13, 37, 49, 541816), 'min_cost': 186.0, 's_vet': [5, 5, 5, 5, 5, 5, 5, 9, 5, 9]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 37, 49, 54362

In [ ]:
h_df = pd.DataFrame(h)
print(h_df)
h_df.to_csv("heuristic_myopic_sol.csv")

              file                 start_time                   end_time  \
0    syntpmed1.txt 2023-07-11 13:37:49.540791 2023-07-11 13:37:49.541816   
1    syntpmed2.txt 2023-07-11 13:37:49.543621 2023-07-11 13:37:49.547756   
2    syntpmed3.txt 2023-07-11 13:37:49.551072 2023-07-11 13:37:49.572642   
3    syntpmed4.txt 2023-07-11 13:37:49.579055 2023-07-11 13:37:49.620068   
4    syntpmed5.txt 2023-07-11 13:37:49.630188 2023-07-11 13:37:49.722173   
5    syntpmed6.txt 2023-07-11 13:37:49.745277 2023-07-11 13:37:49.939815   
6    syntpmed7.txt 2023-07-11 13:37:49.983204 2023-07-11 13:37:50.335644   
7    syntpmed8.txt 2023-07-11 13:37:50.337076 2023-07-11 13:37:50.339974   
8    syntpmed9.txt 2023-07-11 13:37:50.341279 2023-07-11 13:37:50.354913   
9   syntpmed10.txt 2023-07-11 13:37:50.358108 2023-07-11 13:37:50.445623   
10  syntpmed11.txt 2023-07-11 13:37:50.553348 2023-07-11 13:37:50.729817   
11  syntpmed12.txt 2023-07-11 13:37:50.740093 2023-07-11 13:37:51.108971   
12  syntpmed

In [6]:
h_df = pd.read_csv("heuristic_myopic_sol.csv")

h_df[['start_time','end_time']] = h_df[['start_time','end_time']].apply(pd.to_datetime) #if conversion required
h_df['diff_time'] = (h_df['end_time'] - h_df['start_time']).dt.microseconds

h_df

Unnamed: 0            file                 start_time  \
0            0   syntpmed1.txt 2023-07-11 13:37:49.540791   
1            1   syntpmed2.txt 2023-07-11 13:37:49.543621   
2            2   syntpmed3.txt 2023-07-11 13:37:49.551072   
3            3   syntpmed4.txt 2023-07-11 13:37:49.579055   
4            4   syntpmed5.txt 2023-07-11 13:37:49.630188   
5            5   syntpmed6.txt 2023-07-11 13:37:49.745277   
6            6   syntpmed7.txt 2023-07-11 13:37:49.983204   
7            7   syntpmed8.txt 2023-07-11 13:37:50.337076   
8            8   syntpmed9.txt 2023-07-11 13:37:50.341279   
9            9  syntpmed10.txt 2023-07-11 13:37:50.358108   
10          10  syntpmed11.txt 2023-07-11 13:37:50.553348   
11          11  syntpmed12.txt 2023-07-11 13:37:50.740093   
12          12  syntpmed13.txt 2023-07-11 13:37:51.131325   
13          13  syntpmed14.txt 2023-07-11 13:37:51.994796   
14          14  syntpmed15.txt 2023-07-11 13:37:53.452684   
15          15  syntpmed16.txt 2023-07-11 13:37:53.491098   
16          16  syntpmed17.txt 2023-07-11 13:37:53.771801   
17          17  syntpmed18.txt 2023-07-11 13:37:54.338848   
18          18  syntpmed19.txt 2023-07-11 13:37:55.606208   
19          19  syntpmed20.txt 2023-07-11 13:37:58.306178   
20          20  syntpmed21.txt 2023-07-11 13:38:03.026017   
21          21  syntpmed22.txt 2023-07-11 13:38:03.085778   
22          22  syntpmed23.txt 2023-07-11 13:38:03.666062   
23          23  syntpmed24.txt 2023-07-11 13:38:04.780980   
24          24  syntpmed25.txt 2023-07-11 13:38:07.262249   
25          25  syntpmed26.txt 2023-07-11 13:38:12.727191   

                     end_time  min_cost  \
0  2023-07-11 13:37:49.541816     186.0   
1  2023-07-11 13:37:49.547756     372.0   
2  2023-07-11 13:37:49.572642    1368.0   
3  2023-07-11 13:37:49.620068    1905.0   
4  2023-07-11 13:37:49.722173    2708.0   
5  2023-07-11 13:37:49.939815    4389.0   
6  2023-07-11 13:37:50.335644    5801.0   
7  2023-07-11 13:37:50.339974      72.0   
8  2023-07-11 13:37:50.354913     227.0   
9  2023-07-11 13:37:50.445623     672.0   
10 2023-07-11 13:37:50.729817     987.0   
11 2023-07-11 13:37:51.108971    1411.0   
12 2023-07-11 13:37:51.952878    2390.0   
13 2023-07-11 13:37:53.450695    2981.0   
14 2023-07-11 13:37:53.487743      57.0   
15 2023-07-11 13:37:53.766318     282.0   
16 2023-07-11 13:37:54.328352     415.0   
17 2023-07-11 13:37:55.490211     608.0   
18 2023-07-11 13:37:58.262074    1079.0   
19 2023-07-11 13:38:03.023835    1440.0   
20 2023-07-11 13:38:03.082276      14.0   
21 2023-07-11 13:38:03.660516     192.0   
22 2023-07-11 13:38:04.769670     257.0   
23 2023-07-11 13:38:07.141981     378.0   
24 2023-07-11 13:38:12.682412     677.0   
25 2023-07-11 13:38:22.499718    1013.0   

                                                s_vet  diff_time  
0                      [5, 5, 5, 5, 5, 5, 5, 9, 5, 9]       1025  
1   [19, 9, 9, 9, 9, 9, 19, 19, 9, 9, 19, 19, 19, ...       4135  
2   [8, 49, 8, 8, 49, 8, 8, 49, 8, 8, 49, 8, 49, 4...      21570  
3   [48, 69, 69, 69, 69, 69, 69, 48, 69, 69, 48, 6...      41013  
4   [99, 16, 99, 99, 99, 99, 99, 16, 16, 16, 99, 9...      91985  
5   [149, 49, 49, 49, 149, 149, 49, 149, 49, 149, ...     194538  
6   [199, 30, 30, 30, 199, 30, 199, 30, 30, 199, 1...     352440  
7                      [6, 6, 2, 9, 6, 9, 6, 7, 8, 9]       2898  
8   [17, 16, 7, 17, 18, 17, 7, 7, 16, 17, 16, 18, ...      13634  
9   [49, 48, 26, 26, 26, 47, 26, 48, 26, 47, 48, 2...      87515  
10  [68, 69, 67, 10, 66, 10, 67, 10, 69, 10, 10, 6...     176469  
11  [98, 37, 99, 99, 37, 99, 37, 98, 98, 99, 37, 9...     368878  
12  [149, 148, 147, 147, 146, 147, 146, 147, 146, ...     821553  
13  [198, 198, 198, 199, 197, 196, 196, 7, 198, 7,...     455899  
14  [12, 15, 6, 14, 17, 6, 6, 11, 19, 18, 14, 11, ...      35059  
15  [46, 39, 44, 45, 39, 39, 39, 42, 41, 47, 39, 4...     275220  
16  [67, 67, 67, 35, 35, 61, 65, 61, 67, 69, 62, 6...  

## Exchange Solution

### Solver

In [ ]:
def get_random_init_sol(vertices, p):
  return random.choices(range(vertices), k=p)


def heuristic_exchange_solver(vertices, edges, p, cost_mat, sol_init = None):

  # def sol init
  if sol_init is None:
    solution_candidate = get_random_init_sol(vertices, p)
  else:
    solution_candidate = sol_init

  # create sol init instance
  s = Solution(vertices, solution_candidate, cost_mat)
  while not s.solved():
    s.sol_step()


  for i in range(p):
    for j in range(vertices):

      solution_temp = solution_candidate.copy()
      if j in solution_candidate:
        continue

      solution_temp[i] = j
      s_temp = Solution(vertices, solution_temp, cost_mat)

      while not s_temp.solved():
        s_temp.sol_step()

      if s_temp.c < s.c:
        solution_candidate = solution_temp
        s = s_temp
  return s, solution_candidate

In [ ]:
h = []

for pmed in synthetic_pmeds:
  data = get_dataset(pmed)

  start_time =  datetime.datetime.now()
  solutions = heuristic_exchange_solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])
  end_time =  datetime.datetime.now()


  h.append({
      "file": pmed,
      "start_time": start_time,
      "end_time": end_time,
      "min_cost": solutions[0].c,
      "s_vet": solutions[0].s_vet
  })
  print(h)

print(h)

[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 15, 4, 27, 195942), 'end_time': datetime.datetime(2023, 7, 11, 15, 4, 27, 197039), 'min_cost': 157.0, 's_vet': [8, 5, 5, 5, 5, 5, 8, 8, 8, 5]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 15, 4, 27, 195942), 'end_time': datetime.datetime(2023, 7, 11, 15, 4, 27, 197039), 'min_cost': 157.0, 's_vet': [8, 5, 5, 5, 5, 5, 8, 8, 8, 5]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 15, 4, 27, 199324), 'end_time': datetime.datetime(2023, 7, 11, 15, 4, 27, 205605), 'min_cost': 377.0, 's_vet': [3, 3, 3, 3, 11, 11, 11, 11, 3, 11, 11, 11, 11, 11, 11, 11, 3, 11, 3, 11]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 15, 4, 27, 195942), 'end_time': datetime.datetime(2023, 7, 11, 15, 4, 27, 197039), 'min_cost': 157.0, 's_vet': [8, 5, 5, 5, 5, 5, 8, 8, 8, 5]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 15, 4, 27, 199324), 'en

In [ ]:
h_df = pd.DataFrame(h)
print(h_df)
h_df.to_csv("heuristic_exchange_sol.csv")

              file                 start_time                   end_time  \
0    syntpmed1.txt 2023-07-11 15:04:27.195942 2023-07-11 15:04:27.197039   
1    syntpmed2.txt 2023-07-11 15:04:27.199324 2023-07-11 15:04:27.205605   
2    syntpmed3.txt 2023-07-11 15:04:27.209135 2023-07-11 15:04:27.235540   
3    syntpmed4.txt 2023-07-11 15:04:27.240696 2023-07-11 15:04:27.292158   
4    syntpmed5.txt 2023-07-11 15:04:27.409318 2023-07-11 15:04:27.521549   
5    syntpmed6.txt 2023-07-11 15:04:27.543737 2023-07-11 15:04:27.787549   
6    syntpmed7.txt 2023-07-11 15:04:27.828646 2023-07-11 15:04:28.270023   
7    syntpmed8.txt 2023-07-11 15:04:28.271556 2023-07-11 15:04:28.274761   
8    syntpmed9.txt 2023-07-11 15:04:28.276170 2023-07-11 15:04:28.294664   
9   syntpmed10.txt 2023-07-11 15:04:28.298169 2023-07-11 15:04:28.431797   
10  syntpmed11.txt 2023-07-11 15:04:28.437422 2023-07-11 15:04:28.702436   
11  syntpmed12.txt 2023-07-11 15:04:28.712694 2023-07-11 15:04:29.263373   
12  syntpmed

## Exchange Loop Solution

### Solver

In [ ]:
def heuristic_exchange_loop_solver(vertices, edges, p, cost_mat, sol_init = None):

  # def sol init
  if sol_init is None:
    solution_candidate = get_random_init_sol(vertices, p)
  else:
    solution_candidate = sol_init

  solution_candidate.sort()
  solution_candidate_iter = solution_candidate
  solution_candidate = None

  while solution_candidate != solution_candidate_iter:
    solution_candidate = solution_candidate_iter

    s, solution_candidate_iter = heuristic_exchange_solver(vertices, edges, p, cost_mat, solution_candidate)
    solution_candidate_iter.sort()

  return s, solution_candidate

In [ ]:
h = []

for pmed in synthetic_pmeds:
  data = get_dataset(pmed)

  start_time =  datetime.datetime.now()
  solutions = heuristic_exchange_loop_solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])
  end_time =  datetime.datetime.now()


  h.append({
      "file": pmed,
      "start_time": start_time,
      "end_time": end_time,
      "min_cost": solutions[0].c,
      "s_vet": solutions[0].s_vet
  })
  print(h)

print(h)

[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 48, 9, 832749), 'end_time': datetime.datetime(2023, 7, 11, 13, 48, 9, 835016), 'min_cost': 107.0, 's_vet': [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 48, 9, 832749), 'end_time': datetime.datetime(2023, 7, 11, 13, 48, 9, 835016), 'min_cost': 107.0, 's_vet': [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 48, 9, 837203), 'end_time': datetime.datetime(2023, 7, 11, 13, 48, 9, 849025), 'min_cost': 372.0, 's_vet': [19, 9, 9, 9, 9, 9, 19, 19, 9, 9, 19, 19, 19, 19, 19, 9, 19, 19, 9, 19]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 48, 9, 832749), 'end_time': datetime.datetime(2023, 7, 11, 13, 48, 9, 835016), 'min_cost': 107.0, 's_vet': [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 48, 9, 837203), 'end_

In [ ]:
h_df = pd.DataFrame(h)
print(h_df)
h_df.to_csv("heuristic_exchange_loop_sol.csv")

              file                 start_time                   end_time  \
0    syntpmed1.txt 2023-07-11 13:48:09.832749 2023-07-11 13:48:09.835016   
1    syntpmed2.txt 2023-07-11 13:48:09.837203 2023-07-11 13:48:09.849025   
2    syntpmed3.txt 2023-07-11 13:48:09.852064 2023-07-11 13:48:09.904034   
3    syntpmed4.txt 2023-07-11 13:48:09.909605 2023-07-11 13:48:10.013156   
4    syntpmed5.txt 2023-07-11 13:48:10.023326 2023-07-11 13:48:10.243180   
5    syntpmed6.txt 2023-07-11 13:48:10.266321 2023-07-11 13:48:10.746799   
6    syntpmed7.txt 2023-07-11 13:48:10.898570 2023-07-11 13:48:11.777247   
7    syntpmed8.txt 2023-07-11 13:48:11.778768 2023-07-11 13:48:11.785576   
8    syntpmed9.txt 2023-07-11 13:48:11.787089 2023-07-11 13:48:11.839108   
9   syntpmed10.txt 2023-07-11 13:48:11.842619 2023-07-11 13:48:12.229292   
10  syntpmed11.txt 2023-07-11 13:48:12.235024 2023-07-11 13:48:13.042380   
11  syntpmed12.txt 2023-07-11 13:48:13.052421 2023-07-11 13:48:15.794361   
12  syntpmed

In [7]:
h_df = pd.read_csv("heuristic_exchange_loop_sol.csv")

h_df[['start_time','end_time']] = h_df[['start_time','end_time']].apply(pd.to_datetime) #if conversion required
h_df['diff_time'] = (h_df['end_time'] - h_df['start_time']).dt.microseconds

h_df

Unnamed: 0            file                 start_time  \
0            0   syntpmed1.txt 2023-07-11 13:48:09.832749   
1            1   syntpmed2.txt 2023-07-11 13:48:09.837203   
2            2   syntpmed3.txt 2023-07-11 13:48:09.852064   
3            3   syntpmed4.txt 2023-07-11 13:48:09.909605   
4            4   syntpmed5.txt 2023-07-11 13:48:10.023326   
5            5   syntpmed6.txt 2023-07-11 13:48:10.266321   
6            6   syntpmed7.txt 2023-07-11 13:48:10.898570   
7            7   syntpmed8.txt 2023-07-11 13:48:11.778768   
8            8   syntpmed9.txt 2023-07-11 13:48:11.787089   
9            9  syntpmed10.txt 2023-07-11 13:48:11.842619   
10          10  syntpmed11.txt 2023-07-11 13:48:12.235024   
11          11  syntpmed12.txt 2023-07-11 13:48:13.052421   
12          12  syntpmed13.txt 2023-07-11 13:48:15.817355   
13          13  syntpmed14.txt 2023-07-11 13:48:19.582996   
14          14  syntpmed15.txt 2023-07-11 13:48:26.428660   
15          15  syntpmed16.txt 2023-07-11 13:48:26.603424   
16          16  syntpmed17.txt 2023-07-11 13:48:28.853685   
17          17  syntpmed18.txt 2023-07-11 13:48:31.591055   
18          18  syntpmed19.txt 2023-07-11 13:48:39.280379   
19          19  syntpmed20.txt 2023-07-11 13:48:52.578604   
20          20  syntpmed21.txt 2023-07-11 13:49:24.701158   
21          21  syntpmed22.txt 2023-07-11 13:49:24.878067   
22          22  syntpmed23.txt 2023-07-11 13:49:28.167020   
23          23  syntpmed24.txt 2023-07-11 13:49:35.374960   
24          24  syntpmed25.txt 2023-07-11 13:49:47.345296   
25          25  syntpmed26.txt 2023-07-11 13:50:34.208797   

                     end_time  min_cost  \
0  2023-07-11 13:48:09.835016     107.0   
1  2023-07-11 13:48:09.849025     372.0   
2  2023-07-11 13:48:09.904034    1088.0   
3  2023-07-11 13:48:10.013156    1554.0   
4  2023-07-11 13:48:10.243180    2538.0   
5  2023-07-11 13:48:10.746799    4057.0   
6  2023-07-11 13:48:11.777247    5346.0   
7  2023-07-11 13:48:11.785576      38.0   
8  2023-07-11 13:48:11.839108     150.0   
9  2023-07-11 13:48:12.229292     401.0   
10 2023-07-11 13:48:13.042380     667.0   
11 2023-07-11 13:48:15.794361     983.0   
12 2023-07-11 13:48:19.540541    1616.0   
13 2023-07-11 13:48:26.426673    2411.0   
14 2023-07-11 13:48:26.600159      29.0   
15 2023-07-11 13:48:28.747424     149.0   
16 2023-07-11 13:48:31.580559     255.0   
17 2023-07-11 13:48:39.258373     354.0   
18 2023-07-11 13:48:52.535052     644.0   
19 2023-07-11 13:49:24.699264     961.0   
20 2023-07-11 13:49:24.874372       9.0   
21 2023-07-11 13:49:28.161225      79.0   
22 2023-07-11 13:49:35.364844     126.0   
23 2023-07-11 13:49:47.219117     171.0   
24 2023-07-11 13:50:34.166277     384.0   
25 2023-07-11 13:51:59.597213     616.0   

                                                s_vet  diff_time  
0                      [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]       2267  
1   [19, 9, 9, 9, 9, 9, 19, 19, 9, 9, 19, 19, 19, ...      11822  
2   [15, 15, 15, 20, 20, 20, 15, 15, 15, 20, 20, 1...      51970  
3   [48, 3, 3, 3, 3, 3, 48, 48, 3, 3, 48, 48, 3, 4...     103551  
4   [19, 19, 19, 44, 44, 19, 44, 19, 44, 19, 44, 1...     219854  
5   [49, 49, 116, 49, 116, 116, 49, 116, 49, 116, ...     480478  
6   [112, 112, 112, 124, 124, 112, 112, 112, 112, ...     878677  
7                      [6, 6, 2, 9, 4, 9, 6, 7, 9, 9]       6808  
8   [0, 3, 7, 3, 0, 10, 3, 7, 3, 3, 10, 10, 7, 0, ...      52019  
9   [40, 22, 26, 26, 40, 5, 26, 5, 5, 22, 21, 26, ...     386673  
10  [42, 69, 46, 44, 44, 46, 44, 44, 69, 42, 42, 4...     807356  
11  [0, 0, 53, 53, 68, 7, 0, 7, 11, 11, 0, 11, 68,...     741940  
12  [129, 120, 32, 142, 92, 32, 92, 142, 142, 32, ...     723186  
13  [183, 183, 79, 78, 183, 40, 79, 186, 40, 40, 1...     843677  
14  [4, 1, 6, 4, 4, 6, 6, 7, 8, 9, 10, 7, 12, 4, 1...     171499  
15  [46, 23, 19, 23, 4, 5, 39, 42, 12, 39, 5, 19, ...     144000  
16  [67, 24, 67, 35, 35, 24, 64, 37, 67, 37, 45, 3...  

## Exchange + Myopic Solution

### Solver

In [ ]:
def heuristic_exchange_myopic_solver(vertices, edges, p, cost_mat):

  # def sol init
  s_ini, sol_init  = heuristic_myopic_solver(vertices, edges, p, cost_mat)

  # def sol final
  s_final, sol_final = heuristic_exchange_solver(vertices, edges, p, cost_mat, sol_init)

  return s_final, sol_final

In [ ]:
h = []

for pmed in synthetic_pmeds:
  data = get_dataset(pmed)

  start_time =  datetime.datetime.now()
  solutions = heuristic_exchange_myopic_solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])
  end_time =  datetime.datetime.now()


  h.append({
      "file": pmed,
      "start_time": start_time,
      "end_time": end_time,
      "min_cost": solutions[0].c,
      "s_vet": solutions[0].s_vet
  })
  print(h)

print(h)

[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 53, 20, 295020), 'end_time': datetime.datetime(2023, 7, 11, 13, 53, 20, 297018), 'min_cost': 107.0, 's_vet': [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 53, 20, 295020), 'end_time': datetime.datetime(2023, 7, 11, 13, 53, 20, 297018), 'min_cost': 107.0, 's_vet': [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 53, 20, 299096), 'end_time': datetime.datetime(2023, 7, 11, 13, 53, 20, 307490), 'min_cost': 377.0, 's_vet': [3, 3, 3, 3, 11, 11, 11, 11, 3, 11, 11, 11, 11, 11, 11, 11, 3, 11, 3, 11]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 53, 20, 295020), 'end_time': datetime.datetime(2023, 7, 11, 13, 53, 20, 297018), 'min_cost': 107.0, 's_vet': [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 53, 20, 299

In [ ]:
h_df = pd.DataFrame(h)
print(h_df)
h_df.to_csv("heuristic_exchange_myopic_sol.csv")

              file                 start_time                   end_time  \
0    syntpmed1.txt 2023-07-11 13:53:20.295020 2023-07-11 13:53:20.297018   
1    syntpmed2.txt 2023-07-11 13:53:20.299096 2023-07-11 13:53:20.307490   
2    syntpmed3.txt 2023-07-11 13:53:20.310892 2023-07-11 13:53:20.359692   
3    syntpmed4.txt 2023-07-11 13:53:20.365008 2023-07-11 13:53:20.460338   
4    syntpmed5.txt 2023-07-11 13:53:20.469813 2023-07-11 13:53:20.674900   
5    syntpmed6.txt 2023-07-11 13:53:20.805319 2023-07-11 13:53:21.244915   
6    syntpmed7.txt 2023-07-11 13:53:21.284793 2023-07-11 13:53:22.066211   
7    syntpmed8.txt 2023-07-11 13:53:22.067734 2023-07-11 13:53:22.074226   
8    syntpmed9.txt 2023-07-11 13:53:22.075726 2023-07-11 13:53:22.107956   
9   syntpmed10.txt 2023-07-11 13:53:22.111430 2023-07-11 13:53:22.335878   
10  syntpmed11.txt 2023-07-11 13:53:22.341550 2023-07-11 13:53:22.782896   
11  syntpmed12.txt 2023-07-11 13:53:22.793198 2023-07-11 13:53:23.708886   
12  syntpmed

## Exchange Loop + Myopic Solution

### Solver

In [ ]:
def heuristic_exchange_loop_myopic_solver(vertices, edges, p, cost_mat):

  # def sol init
  s_ini, sol_init  = heuristic_myopic_solver(vertices, edges, p, cost_mat)

  # def sol final
  s_final, sol_final = heuristic_exchange_loop_solver(vertices, edges, p, cost_mat, sol_init)

  return s_final, sol_final

In [ ]:
h = []

for pmed in synthetic_pmeds:
  data = get_dataset(pmed)

  start_time =  datetime.datetime.now()
  solutions = heuristic_exchange_loop_myopic_solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])
  end_time =  datetime.datetime.now()


  h.append({
      "file": pmed,
      "start_time": start_time,
      "end_time": end_time,
      "min_cost": solutions[0].c,
      "s_vet": solutions[0].s_vet
  })
  print(h)

print(h)

[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 57, 26, 776366), 'end_time': datetime.datetime(2023, 7, 11, 13, 57, 26, 780982), 'min_cost': 107.0, 's_vet': [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 57, 26, 776366), 'end_time': datetime.datetime(2023, 7, 11, 13, 57, 26, 780982), 'min_cost': 107.0, 's_vet': [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 57, 26, 782869), 'end_time': datetime.datetime(2023, 7, 11, 13, 57, 26, 794476), 'min_cost': 372.0, 's_vet': [19, 9, 9, 9, 9, 9, 19, 19, 9, 9, 19, 19, 19, 19, 19, 9, 19, 19, 9, 19]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 57, 26, 776366), 'end_time': datetime.datetime(2023, 7, 11, 13, 57, 26, 780982), 'min_cost': 107.0, 's_vet': [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 13, 57, 26, 78286

In [ ]:
h_df = pd.DataFrame(h)
print(h_df)
h_df.to_csv("heuristic_exchange_loop_myopic_sol.csv")

              file                 start_time                   end_time  \
0    syntpmed1.txt 2023-07-11 13:57:26.776366 2023-07-11 13:57:26.780982   
1    syntpmed2.txt 2023-07-11 13:57:26.782869 2023-07-11 13:57:26.794476   
2    syntpmed3.txt 2023-07-11 13:57:26.797785 2023-07-11 13:57:26.899877   
3    syntpmed4.txt 2023-07-11 13:57:27.011289 2023-07-11 13:57:27.157017   
4    syntpmed5.txt 2023-07-11 13:57:27.167745 2023-07-11 13:57:27.586290   
5    syntpmed6.txt 2023-07-11 13:57:27.608211 2023-07-11 13:57:28.298823   
6    syntpmed7.txt 2023-07-11 13:57:28.338404 2023-07-11 13:57:29.556274   
7    syntpmed8.txt 2023-07-11 13:57:29.557827 2023-07-11 13:57:29.567051   
8    syntpmed9.txt 2023-07-11 13:57:29.568576 2023-07-11 13:57:29.653953   
9   syntpmed10.txt 2023-07-11 13:57:29.657354 2023-07-11 13:57:30.274380   
10  syntpmed11.txt 2023-07-11 13:57:30.280060 2023-07-11 13:57:30.992556   
11  syntpmed12.txt 2023-07-11 13:57:31.002889 2023-07-11 13:57:33.015041   
12  syntpmed

## Myopic Solution with Exchange Correction

### Solver

In [ ]:
def exchange_correction(vertices, edges, p, cost_mat, sol_candidate):
  # create sol init instance
  s = Solution(vertices, sol_candidate, cost_mat)
  while not s.solved():
    s.sol_step()

  for i in range(len(sol_candidate) - 1, -1, -1):
    for j in range(vertices):

      solution_temp = sol_candidate.copy()
      if j in sol_candidate:
        continue

      solution_temp[i] = j
      s_temp = Solution(vertices, solution_temp, cost_mat)

      while not s_temp.solved():
        s_temp.sol_step()

      if s_temp.c < s.c:
        sol_candidate = solution_temp
        s = s_temp
  return s, sol_candidate


def heuristic_myopic_with_exchange_corr_solver(vertices, edges, p, cost_mat):

  # create solutions instances
  solution_candidate = []
  s = None
  while len(solution_candidate) < p:
    s_list = solution_candidate.copy()
    s_list_temp = solution_candidate.copy()
    s_list_temp.append(-1)
    s_cost = float("inf")
    s_temp = None

    # myopic add
    for i in range(vertices):
      if i not in s_list:
        s_list_temp[len(solution_candidate)] = i
        s_temp = Solution(vertices, s_list_temp, cost_mat)

        while not s_temp.solved():
          s_temp.sol_step()

        if s_cost > s_temp.c:
          s_list = s_list_temp
          s_cost = s_temp.c
          s = s_temp

    solution_candidate = s_list

    # exchange correction
    s, solution_candidate = exchange_correction(vertices, edges, p, cost_mat, solution_candidate)
  return s, solution_candidate

In [ ]:
h = []

for pmed in synthetic_pmeds:
  data = get_dataset(pmed)

  start_time =  datetime.datetime.now()
  solutions = heuristic_myopic_with_exchange_corr_solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])
  end_time =  datetime.datetime.now()

  h.append({
      "file": pmed,
      "start_time": start_time,
      "end_time": end_time,
      "min_cost": solutions[0].c,
      "s_vet": solutions[0].s_vet
  })
  print(h)

print(h)

[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 14, 2, 31, 765847), 'end_time': datetime.datetime(2023, 7, 11, 14, 2, 31, 769125), 'min_cost': 107.0, 's_vet': [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 14, 2, 31, 765847), 'end_time': datetime.datetime(2023, 7, 11, 14, 2, 31, 769125), 'min_cost': 107.0, 's_vet': [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 14, 2, 31, 770641), 'end_time': datetime.datetime(2023, 7, 11, 14, 2, 31, 781605), 'min_cost': 377.0, 's_vet': [3, 3, 3, 3, 11, 11, 11, 11, 3, 11, 11, 11, 11, 11, 11, 11, 3, 11, 3, 11]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 14, 2, 31, 765847), 'end_time': datetime.datetime(2023, 7, 11, 14, 2, 31, 769125), 'min_cost': 107.0, 's_vet': [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 14, 2, 31, 770641), 'en

In [ ]:
h_df = pd.DataFrame(h)
print(h_df)
h_df.to_csv("heuristic_myopic_with_exchange_corr_sol.csv")

              file                 start_time                   end_time  \
0    syntpmed1.txt 2023-07-11 14:02:31.765847 2023-07-11 14:02:31.769125   
1    syntpmed2.txt 2023-07-11 14:02:31.770641 2023-07-11 14:02:31.781605   
2    syntpmed3.txt 2023-07-11 14:02:31.785843 2023-07-11 14:02:31.842643   
3    syntpmed4.txt 2023-07-11 14:02:31.848169 2023-07-11 14:02:31.959142   
4    syntpmed5.txt 2023-07-11 14:02:31.969514 2023-07-11 14:02:32.203791   
5    syntpmed6.txt 2023-07-11 14:02:32.227192 2023-07-11 14:02:32.745097   
6    syntpmed7.txt 2023-07-11 14:02:32.899705 2023-07-11 14:02:33.808258   
7    syntpmed8.txt 2023-07-11 14:02:33.808869 2023-07-11 14:02:33.821607   
8    syntpmed9.txt 2023-07-11 14:02:33.823103 2023-07-11 14:02:33.880811   
9   syntpmed10.txt 2023-07-11 14:02:33.884469 2023-07-11 14:02:34.293438   
10  syntpmed11.txt 2023-07-11 14:02:34.299247 2023-07-11 14:02:35.097052   
11  syntpmed12.txt 2023-07-11 14:02:35.107677 2023-07-11 14:02:36.750200   
12  syntpmed

In [8]:
h_df = pd.read_csv("heuristic_myopic_with_exchange_corr_sol.csv")

h_df[['start_time','end_time']] = h_df[['start_time','end_time']].apply(pd.to_datetime) #if conversion required
h_df['diff_time'] = (h_df['end_time'] - h_df['start_time']).dt.microseconds

h_df

Unnamed: 0            file                 start_time  \
0            0   syntpmed1.txt 2023-07-11 14:02:31.765847   
1            1   syntpmed2.txt 2023-07-11 14:02:31.770641   
2            2   syntpmed3.txt 2023-07-11 14:02:31.785843   
3            3   syntpmed4.txt 2023-07-11 14:02:31.848169   
4            4   syntpmed5.txt 2023-07-11 14:02:31.969514   
5            5   syntpmed6.txt 2023-07-11 14:02:32.227192   
6            6   syntpmed7.txt 2023-07-11 14:02:32.899705   
7            7   syntpmed8.txt 2023-07-11 14:02:33.808869   
8            8   syntpmed9.txt 2023-07-11 14:02:33.823103   
9            9  syntpmed10.txt 2023-07-11 14:02:33.884469   
10          10  syntpmed11.txt 2023-07-11 14:02:34.299247   
11          11  syntpmed12.txt 2023-07-11 14:02:35.107677   
12          12  syntpmed13.txt 2023-07-11 14:02:36.772022   
13          13  syntpmed14.txt 2023-07-11 14:02:40.541618   
14          14  syntpmed15.txt 2023-07-11 14:02:47.211647   
15          15  syntpmed16.txt 2023-07-11 14:02:47.464012   
16          16  syntpmed17.txt 2023-07-11 14:02:49.532652   
17          17  syntpmed18.txt 2023-07-11 14:02:53.849461   
18          18  syntpmed19.txt 2023-07-11 14:03:02.849367   
19          19  syntpmed20.txt 2023-07-11 14:03:23.551764   
20          20  syntpmed21.txt 2023-07-11 14:04:00.685499   
21          21  syntpmed22.txt 2023-07-11 14:04:01.207456   
22          22  syntpmed23.txt 2023-07-11 14:04:06.849801   
23          23  syntpmed24.txt 2023-07-11 14:04:18.860923   
24          24  syntpmed25.txt 2023-07-11 14:04:44.837406   
25          25  syntpmed26.txt 2023-07-11 14:05:44.857484   

                     end_time  min_cost  \
0  2023-07-11 14:02:31.769125     107.0   
1  2023-07-11 14:02:31.781605     377.0   
2  2023-07-11 14:02:31.842643    1088.0   
3  2023-07-11 14:02:31.959142    1554.0   
4  2023-07-11 14:02:32.203791    2439.0   
5  2023-07-11 14:02:32.745097    4057.0   
6  2023-07-11 14:02:33.808258    5391.0   
7  2023-07-11 14:02:33.821607      38.0   
8  2023-07-11 14:02:33.880811     150.0   
9  2023-07-11 14:02:34.293438     431.0   
10 2023-07-11 14:02:35.097052     663.0   
11 2023-07-11 14:02:36.750200    1022.0   
12 2023-07-11 14:02:40.499756    1649.0   
13 2023-07-11 14:02:47.209751    2307.0   
14 2023-07-11 14:02:47.460242      29.0   
15 2023-07-11 14:02:49.526633     139.0   
16 2023-07-11 14:02:53.736613     256.0   
17 2023-07-11 14:03:02.826657     385.0   
18 2023-07-11 14:03:23.510361     641.0   
19 2023-07-11 14:04:00.683260     868.0   
20 2023-07-11 14:04:01.203535       9.0   
21 2023-07-11 14:04:06.843770      79.0   
22 2023-07-11 14:04:18.850297     120.0   
23 2023-07-11 14:04:44.709061     174.0   
24 2023-07-11 14:05:44.816647     364.0   
25 2023-07-11 14:07:32.492592     559.0   

                                                s_vet  diff_time  
0                      [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]       3278  
1   [3, 3, 3, 3, 11, 11, 11, 11, 3, 11, 11, 11, 11...      10964  
2   [15, 15, 15, 20, 20, 20, 15, 15, 15, 20, 20, 1...      56800  
3   [48, 3, 3, 3, 3, 3, 48, 48, 3, 3, 48, 48, 3, 4...     110973  
4   [66, 66, 61, 61, 66, 61, 61, 61, 61, 61, 66, 6...     234277  
5   [49, 49, 116, 49, 116, 116, 49, 116, 49, 116, ...     517905  
6   [195, 112, 112, 112, 195, 195, 112, 112, 112, ...     908553  
7                      [6, 6, 2, 9, 4, 9, 6, 7, 9, 9]      12738  
8   [0, 3, 7, 3, 0, 10, 3, 7, 3, 3, 10, 10, 7, 0, ...      57708  
9   [36, 31, 26, 26, 36, 5, 26, 31, 5, 5, 31, 26, ...     408969  
10  [42, 69, 33, 44, 44, 44, 33, 44, 69, 33, 33, 4...     797805  
11  [49, 69, 49, 25, 19, 57, 49, 57, 69, 25, 49, 1...     642523  
12  [35, 97, 17, 111, 111, 111, 21, 17, 111, 21, 1...     727734  
13  [0, 134, 5, 0, 146, 5, 0, 134, 134, 134, 134, ...     668133  
14  [4, 1, 6, 4, 4, 6, 6, 7, 8, 9, 10, 7, 12, 4, 1...     248595  
15  [0, 20, 19, 3, 37, 5, 35, 42, 12, 3, 5, 19, 12...      62621  
16  [67, 1, 22, 35, 4, 33, 64, 20, 22, 14, 1, 4, 3...  

## Myopic Solution with Exchange Correction Loop

### Solver

In [ ]:
def exchange_correction_loop(vertices, edges, p, cost_mat, sol_candidate):
  # create sol init instance
  s = Solution(vertices, sol_candidate, cost_mat)
  while not s.solved():
    s.sol_step()

  sol_candidate.sort()
  sol_test = None
  while sol_test != sol_candidate:
    sol_test = sol_candidate.copy()
    for i in range(len(sol_candidate) - 1, -1, -1):
      for j in range(vertices):

        solution_temp = sol_candidate.copy()
        if j in sol_candidate:
          continue

        solution_temp[i] = j
        s_temp = Solution(vertices, solution_temp, cost_mat)

        while not s_temp.solved():
          s_temp.sol_step()

        if s_temp.c < s.c:
          sol_candidate = solution_temp
          s = s_temp
    sol_candidate.sort()
  return s, sol_candidate


def heuristic_myopic_with_exchange_corr_loop_solver(vertices, edges, p, cost_mat):

  # create solutions instances
  solution_candidate = []
  s = None
  while len(solution_candidate) < p:
    s_list = solution_candidate.copy()
    s_list_temp = solution_candidate.copy()
    s_list_temp.append(-1)
    s_cost = float("inf")
    s_temp = None

    # myopic add
    for i in range(vertices):
      if i not in s_list:
        s_list_temp[len(solution_candidate)] = i
        s_temp = Solution(vertices, s_list_temp, cost_mat)

        while not s_temp.solved():
          s_temp.sol_step()

        if s_cost > s_temp.c:
          s_list = s_list_temp
          s_cost = s_temp.c
          s = s_temp

    solution_candidate = s_list

    # exchange correction
    s, solution_candidate = exchange_correction_loop(vertices, edges, p, cost_mat, solution_candidate)
  return s, solution_candidate

In [ ]:
h = []

for pmed in synthetic_pmeds:
  data = get_dataset(pmed)

  start_time =  datetime.datetime.now()
  solutions = heuristic_myopic_with_exchange_corr_loop_solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])
  end_time =  datetime.datetime.now()

  h.append({
      "file": pmed,
      "start_time": start_time,
      "end_time": end_time,
      "min_cost": solutions[0].c,
      "s_vet": solutions[0].s_vet
  })
  print(h)

print(h)

[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 16, 43, 32, 198781), 'end_time': datetime.datetime(2023, 7, 11, 16, 43, 32, 203543), 'min_cost': 107.0, 's_vet': [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 16, 43, 32, 198781), 'end_time': datetime.datetime(2023, 7, 11, 16, 43, 32, 203543), 'min_cost': 107.0, 's_vet': [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 16, 43, 32, 204947), 'end_time': datetime.datetime(2023, 7, 11, 16, 43, 32, 219161), 'min_cost': 377.0, 's_vet': [3, 3, 3, 3, 11, 11, 11, 11, 3, 11, 11, 11, 11, 11, 11, 11, 3, 11, 3, 11]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 16, 43, 32, 198781), 'end_time': datetime.datetime(2023, 7, 11, 16, 43, 32, 203543), 'min_cost': 107.0, 's_vet': [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 16, 43, 32, 204

In [ ]:
h_df = pd.DataFrame(h)
print(h_df)
h_df.to_csv("heuristic_myopic_with_exchange_corr_loop_sol.csv")

              file                 start_time                   end_time  \
0    syntpmed1.txt 2023-07-11 16:43:32.198781 2023-07-11 16:43:32.203543   
1    syntpmed2.txt 2023-07-11 16:43:32.204947 2023-07-11 16:43:32.219161   
2    syntpmed3.txt 2023-07-11 16:43:32.222919 2023-07-11 16:43:32.312749   
3    syntpmed4.txt 2023-07-11 16:43:32.318204 2023-07-11 16:43:32.497280   
4    syntpmed5.txt 2023-07-11 16:43:32.507882 2023-07-11 16:43:32.876119   
5    syntpmed6.txt 2023-07-11 16:43:32.898391 2023-07-11 16:43:33.721047   
6    syntpmed7.txt 2023-07-11 16:43:33.874849 2023-07-11 16:43:35.820533   
7    syntpmed8.txt 2023-07-11 16:43:35.822136 2023-07-11 16:43:35.840711   
8    syntpmed9.txt 2023-07-11 16:43:35.842220 2023-07-11 16:43:35.943210   
9   syntpmed10.txt 2023-07-11 16:43:35.946856 2023-07-11 16:43:36.637515   
10  syntpmed11.txt 2023-07-11 16:43:36.643163 2023-07-11 16:43:38.026999   
11  syntpmed12.txt 2023-07-11 16:43:38.037343 2023-07-11 16:43:40.940074   
12  syntpmed

In [9]:
h_df = pd.read_csv("heuristic_myopic_with_exchange_corr_loop_sol.csv")

h_df[['start_time','end_time']] = h_df[['start_time','end_time']].apply(pd.to_datetime) #if conversion required
h_df['diff_time'] = (h_df['end_time'] - h_df['start_time']).dt.microseconds

h_df

Unnamed: 0            file                 start_time  \
0            0   syntpmed1.txt 2023-07-11 16:43:32.198781   
1            1   syntpmed2.txt 2023-07-11 16:43:32.204947   
2            2   syntpmed3.txt 2023-07-11 16:43:32.222919   
3            3   syntpmed4.txt 2023-07-11 16:43:32.318204   
4            4   syntpmed5.txt 2023-07-11 16:43:32.507882   
5            5   syntpmed6.txt 2023-07-11 16:43:32.898391   
6            6   syntpmed7.txt 2023-07-11 16:43:33.874849   
7            7   syntpmed8.txt 2023-07-11 16:43:35.822136   
8            8   syntpmed9.txt 2023-07-11 16:43:35.842220   
9            9  syntpmed10.txt 2023-07-11 16:43:35.946856   
10          10  syntpmed11.txt 2023-07-11 16:43:36.643163   
11          11  syntpmed12.txt 2023-07-11 16:43:38.037343   
12          12  syntpmed13.txt 2023-07-11 16:43:40.961994   
13          13  syntpmed14.txt 2023-07-11 16:43:47.661827   
14          14  syntpmed15.txt 2023-07-11 16:43:59.273325   
15          15  syntpmed16.txt 2023-07-11 16:43:59.728555   
16          16  syntpmed17.txt 2023-07-11 16:44:03.561284   
17          17  syntpmed18.txt 2023-07-11 16:44:12.281435   
18          18  syntpmed19.txt 2023-07-11 16:44:28.795115   
19          19  syntpmed20.txt 2023-07-11 16:45:07.176885   
20          20  syntpmed21.txt 2023-07-11 16:46:20.731869   
21          21  syntpmed22.txt 2023-07-11 16:46:21.745901   
22          22  syntpmed23.txt 2023-07-11 16:46:33.668460   
23          23  syntpmed24.txt 2023-07-11 16:46:58.598010   
24          24  syntpmed25.txt 2023-07-11 16:47:50.307740   
25          25  syntpmed26.txt 2023-07-11 16:49:44.813033   

                     end_time  min_cost  \
0  2023-07-11 16:43:32.203543     107.0   
1  2023-07-11 16:43:32.219161     377.0   
2  2023-07-11 16:43:32.312749    1088.0   
3  2023-07-11 16:43:32.497280    1554.0   
4  2023-07-11 16:43:32.876119    2439.0   
5  2023-07-11 16:43:33.721047    4057.0   
6  2023-07-11 16:43:35.820533    5346.0   
7  2023-07-11 16:43:35.840711      42.0   
8  2023-07-11 16:43:35.943210     150.0   
9  2023-07-11 16:43:36.637515     431.0   
10 2023-07-11 16:43:38.026999     663.0   
11 2023-07-11 16:43:40.940074    1022.0   
12 2023-07-11 16:43:47.622024    1680.0   
13 2023-07-11 16:43:59.270559    2288.0   
14 2023-07-11 16:43:59.724856      29.0   
15 2023-07-11 16:44:03.555313     139.0   
16 2023-07-11 16:44:12.171565     257.0   
17 2023-07-11 16:44:28.772456     385.0   
18 2023-07-11 16:45:07.137325     641.0   
19 2023-07-11 16:46:20.729976     868.0   
20 2023-07-11 16:46:21.742021       9.0   
21 2023-07-11 16:46:33.662383      81.0   
22 2023-07-11 16:46:58.586507     120.0   
23 2023-07-11 16:47:50.179186     174.0   
24 2023-07-11 16:49:44.772942     361.0   
25 2023-07-11 16:53:11.422315     559.0   

                                                s_vet  diff_time  
0                      [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]       4762  
1   [3, 3, 3, 3, 11, 11, 11, 11, 3, 11, 11, 11, 11...      14214  
2   [15, 15, 15, 20, 20, 20, 15, 15, 15, 20, 20, 1...      89830  
3   [48, 3, 3, 3, 3, 3, 48, 48, 3, 3, 48, 48, 3, 4...     179076  
4   [66, 66, 61, 61, 66, 61, 61, 61, 61, 61, 66, 6...     368237  
5   [49, 49, 116, 49, 116, 116, 49, 116, 49, 116, ...     822656  
6   [112, 112, 112, 124, 124, 112, 112, 112, 112, ...     945684  
7                      [6, 6, 2, 3, 4, 3, 6, 6, 8, 8]      18575  
8   [0, 3, 7, 3, 0, 10, 3, 7, 3, 3, 10, 10, 7, 0, ...     100990  
9   [36, 31, 26, 26, 36, 5, 26, 31, 5, 5, 31, 26, ...     690659  
10  [42, 69, 33, 44, 44, 44, 33, 44, 69, 33, 33, 4...     383836  
11  [49, 69, 49, 25, 19, 57, 49, 57, 69, 25, 49, 1...     902731  
12  [97, 78, 97, 23, 111, 111, 23, 28, 111, 78, 78...     660030  
13  [34, 176, 176, 176, 146, 153, 34, 134, 134, 13...     608732  
14  [4, 1, 6, 4, 4, 6, 6, 7, 8, 9, 10, 7, 12, 4, 1...     451531  
15  [0, 20, 19, 3, 37, 5, 35, 42, 12, 3, 5, 19, 12...     826758  
16  [0, 1, 22, 35, 1, 33, 64, 20, 22, 14, 1, 16, 0...  

## Myopic Solution with Exchange Correction and Exchange Loop Fine

### Solver

In [ ]:
def heuristic_myopic_with_exchange_corr_and_exchange_fine_solver(vertices, edges, p, cost_mat):

  # def sol init
  s_ini, sol_init  = heuristic_myopic_with_exchange_corr_solver(vertices, edges, p, cost_mat)

  # def sol final
  s_final, sol_final = heuristic_exchange_loop_solver(vertices, edges, p, cost_mat, sol_init)

  return s_final, sol_final

In [ ]:
h = []

for pmed in synthetic_pmeds:
  data = get_dataset(pmed)

  start_time =  datetime.datetime.now()
  solutions = heuristic_myopic_with_exchange_corr_and_exchange_fine_solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])
  end_time =  datetime.datetime.now()

  h.append({
      "file": pmed,
      "start_time": start_time,
      "end_time": end_time,
      "min_cost": solutions[0].c,
      "s_vet": solutions[0].s_vet
  })
  print(h)

print(h)

[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 14, 7, 32, 558240), 'end_time': datetime.datetime(2023, 7, 11, 14, 7, 32, 561388), 'min_cost': 107.0, 's_vet': [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 14, 7, 32, 558240), 'end_time': datetime.datetime(2023, 7, 11, 14, 7, 32, 561388), 'min_cost': 107.0, 's_vet': [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 14, 7, 32, 562276), 'end_time': datetime.datetime(2023, 7, 11, 14, 7, 32, 575783), 'min_cost': 377.0, 's_vet': [3, 3, 3, 3, 11, 11, 11, 11, 3, 11, 11, 11, 11, 11, 11, 11, 3, 11, 3, 11]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 14, 7, 32, 558240), 'end_time': datetime.datetime(2023, 7, 11, 14, 7, 32, 561388), 'min_cost': 107.0, 's_vet': [5, 5, 5, 5, 5, 5, 7, 7, 7, 7]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 14, 7, 32, 562276), 'en

In [ ]:
h_df = pd.DataFrame(h)
print(h_df)
h_df.to_csv("heuristic_myopic_with_exchange_corr_and_exchange_fine_sol.csv")

              file                 start_time                   end_time  \
0    syntpmed1.txt 2023-07-11 14:07:32.558240 2023-07-11 14:07:32.561388   
1    syntpmed2.txt 2023-07-11 14:07:32.562276 2023-07-11 14:07:32.575783   
2    syntpmed3.txt 2023-07-11 14:07:32.578628 2023-07-11 14:07:32.664775   
3    syntpmed4.txt 2023-07-11 14:07:32.670750 2023-07-11 14:07:32.836627   
4    syntpmed5.txt 2023-07-11 14:07:32.847119 2023-07-11 14:07:33.185784   
5    syntpmed6.txt 2023-07-11 14:07:33.208148 2023-07-11 14:07:33.967060   
6    syntpmed7.txt 2023-07-11 14:07:34.116978 2023-07-11 14:07:35.906448   
7    syntpmed8.txt 2023-07-11 14:07:35.907893 2023-07-11 14:07:35.922460   
8    syntpmed9.txt 2023-07-11 14:07:35.923919 2023-07-11 14:07:35.999263   
9   syntpmed10.txt 2023-07-11 14:07:36.002948 2023-07-11 14:07:36.537717   
10  syntpmed11.txt 2023-07-11 14:07:36.543817 2023-07-11 14:07:37.604307   
11  syntpmed12.txt 2023-07-11 14:07:37.615657 2023-07-11 14:07:39.815164   
12  syntpmed

## Results

In [ ]:

results = [
    "/content/P-Median-Problem/heuristic_exchange_loop_myopic_sol.csv",
    "/content/P-Median-Problem/heuristic_exchange_loop_sol.csv",
    "/content/P-Median-Problem/heuristic_exchange_myopic_sol.csv",
    "/content/P-Median-Problem/heuristic_exchange_sol.csv",
    "/content/P-Median-Problem/heuristic_myopic_sol.csv",
    "/content/P-Median-Problem/heuristic_myopic_with_exchange_corr_and_exchange_fine_sol.csv",
    "/content/P-Median-Problem/heuristic_myopic_with_exchange_corr_sol.csv"
]

In [ ]:
for pmed in synthetic_pmeds:
  data = get_dataset(pmed)

  print(pmed, data["vertices"], data["p"])

syntpmed1.txt 10 2
syntpmed2.txt 20 2
syntpmed3.txt 50 2
syntpmed4.txt 70 2
syntpmed5.txt 100 2
syntpmed6.txt 150 2
syntpmed7.txt 200 2
syntpmed8.txt 10 5
syntpmed9.txt 20 5
syntpmed10.txt 50 5
syntpmed11.txt 70 5
syntpmed12.txt 100 5
syntpmed13.txt 150 5
syntpmed14.txt 200 5
syntpmed15.txt 20 10
syntpmed16.txt 50 10
syntpmed17.txt 70 10
syntpmed18.txt 100 10
syntpmed19.txt 150 10
syntpmed20.txt 200 10
syntpmed21.txt 20 15
syntpmed22.txt 50 15
syntpmed23.txt 70 15
syntpmed24.txt 100 15
syntpmed25.txt 150 15
syntpmed26.txt 200 15
