<a href="https://colab.research.google.com/github/JuniorDurand/P-Median-Problem/blob/main/P_medianas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Problema das P-medianas

## Environment

In [1]:
import os
import numpy as np
import itertools
from itertools import combinations
from random import randint
import datetime
import heapq
import pandas as pd
import random

In [2]:
!git clone https://github.com/JuniorDurand/P-Median-Problem.git

os.chdir("P-Median-Problem")

Cloning into 'P-Median-Problem'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 26 (delta 4), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (26/26), 47.45 KiB | 899.00 KiB/s, done.


## Dataset

### Synthetic Dataset

In [3]:
vertices = [10, 20, 50, 70, 100, 150, 200]
ps = [2, 5, 10, 15]
count = 1
synthetic_pmeds = []

for p in ps:
  for v in vertices:

    if p >= v:
      continue

    file_path = "syntpmed{count}.txt".format(count=count)

    if os.path.isfile(file_path):
      count = count + 1
      synthetic_pmeds.append(file_path)
      continue

    arq = open(file_path, "a")

    # head of file
    arq.write("{v} {p}\n".format(v=v, p=p))
    for i in combinations(range(v), 2):

      # define rand cost
      c = randint(0,100)
      # writer edge line
      arq.write("{i} {j} {c}\n".format(i=i[0]+1, j=i[1]+1, c=c))

    arq.close()
    count = count + 1
    synthetic_pmeds.append(file_path)




### Brunel Dataset

[Brunel Dataset](http://people.brunel.ac.uk/~mastjjb/jeb/orlib/pmedinfo.html)

The graphs resulting from this dataset are not complete so they were not used in the analysis

In [ ]:
brunel_pmeds = [
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed1.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed2.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed3.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed4.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed5.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed6.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed7.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed8.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed9.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed10.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed11.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed12.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed13.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed14.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed15.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed16.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed17.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed18.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed19.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed20.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed21.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed22.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed23.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed24.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed25.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed26.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed27.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed28.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed29.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed30.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed31.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed32.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed33.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed34.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed35.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed36.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed37.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed38.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed39.txt",
    "http://people.brunel.ac.uk/~mastjjb/jeb/orlib/files/pmed40.txt",
]

In [ ]:
for pmed in brunel_pmeds:
  os.system('wget {FILE}'.format(FILE = pmed))

In [ ]:
def get_dataset(filepath):
  with open(filepath.split('/')[-1]) as f:
    content = f.readlines()

  params = content[0].split()
  params = [int(x) for x in params]

  # def dataset parans
  vertices = params[0]
  p = params[1]
  edges = 0

  # preprocess cost edges
  cost = [x.split() for x in content[1:]]
  cost = [list(map(int, x)) for x in cost]

  # create mat cost
  cost_mat = np.full((vertices, vertices), np.nan)
  for i, j, c in cost:
    cost_mat[i-1][j-1] = c
    cost_mat[j-1][i-1] = c

  for i in range(vertices):
    cost_mat[i][i] = 0

  return {
      "vertices" : vertices,
      "edges": edges,
      "p": p,
      "cost_mat": cost_mat
  }


## Linear Solution

###Utility Functions

#### Binary count

In [ ]:
class BinaryCount:
  def __init__(self, length: int, start: int = 0):
    self.length = length
    self.start = start
    self.i = self.start

  def __get_zeros(self, n):
    zeros = ""
    for i in range(n):
      zeros = zeros + str(0)

    return zeros

  def __string_to_list_int(self, string):
    bin_list = [*string]
    bin_list = [ int(x) for x in bin_list]
    return bin_list

  def __next__(self):
    bin_code = "{number:b}".format(number=self.i)
    self.i = self.i + 1

    if(len(bin_code) < self.length):
      bin_code = self.__get_zeros(self.length - len(bin_code)) + bin_code

    elif (len(bin_code) == self.length):
      bin_code = bin_code

    else:
      raise StopIteration

    # return bin_code
    return self.__string_to_list_int(bin_code)

  def __iter__(self):
    return self


#### Get cost of solution

In [ ]:
def get_cost_sol(vertices, sol, cost_mat):
  total_cost = 0
  for i in range(vertices):
    for j in range(vertices):
      if not np.isnan(cost_mat[i][j]):
        total_cost = total_cost + (cost_mat[i][j] * sol[i][j])
      elif( sol[i][j] > 0):
        raise Exception
      else:
        continue;
  return total_cost



#### Check all served vertices restriction

In [ ]:
def restriction_all_served(vertices, sol):
  sol = np.array(sol)
  for i in range(vertices):
    col = sol[:, i]
    sum = np.sum(col)
    if(sum != 1):
      return False
  return True

sol_test = [[0,1,0], [1,0,0], [0,0,0]]
restriction_all_served(3, sol_test)

False

#### Check number of servers restriction

In [ ]:
def restriction_p_servers(vertices, p, sol):
  sol = np.array(sol)

  col = sol[:, vertices]
  sum = np.sum(col)
  if(sum != p):
    return False
  return True

sol_test = [[0,1,0,0], [1,0,0,1], [0,0,0,0]]
restriction_p_servers(3, 2, sol_test)

False

#### Check vertives served by open servers

In [ ]:
def restriction_served_by_open_servers(vertices, sol):
  sol = np.array(sol)

  for i in range(vertices):
    row = sol[i, :vertices]
    for j in row:
      if not(j - sol[i,vertices] <= 0):
        # print(i, row, sol[i,vertices])
        return False
  return True

sol_test = [[0,1,0,1], [1,0,0,1], [0,0,0,1]]
restriction_served_by_open_servers(3, sol_test)

True

### Solver

In [ ]:
def linear_solver(vertices, edges, p, cost_mat):
  solutions = []

  bin_count = BinaryCount( vertices * (vertices + 1) )

  for bin in bin_count:
    sol = np.array(bin)
    sol = np.reshape(sol, (vertices, (vertices + 1)))


    if not restriction_p_servers(vertices, p, sol):
      continue;

    if not restriction_all_served(vertices, sol):
      continue;

    if not restriction_served_by_open_servers(vertices, sol):
      continue;
    # print(sol)

    cost = get_cost_sol(vertices, sol, cost_mat)

    solutions.append([cost, sol])

  return solutions








### Execute Solution

In [ ]:
data = get_dataset('./pmed00.txt')

print(data)

solutions = linear_solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])

solutions.sort(key=lambda s : s[0])


print("Best cost: ", solutions[0][0])
print("Best solution matrix: \n", solutions[0][1])

{'vertices': 4, 'edges': 40, 'p': 2, 'cost_mat': array([[ 0., 34., 32., 66.],
       [34.,  0., 73., 63.],
       [32., 73.,  0., 92.],
       [66., 63., 92.,  0.]])}
66.0
[[1 1 1 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 1]]
95.0
[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 1 0 1]
 [0 1 0 1 1]]
95.0
[[0 0 0 0 0]
 [0 1 0 1 1]
 [1 0 1 0 1]
 [0 0 0 0 0]]
95.0
[[1 0 1 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 1 1]]
95.0
[[1 0 1 0 1]
 [0 1 0 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]
97.0
[[0 0 0 0 0]
 [1 1 0 1 1]
 [0 0 1 0 1]
 [0 0 0 0 0]]
98.0
[[1 0 1 1 1]
 [0 1 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]
100.0
[[1 1 0 1 1]
 [0 0 0 0 0]
 [0 0 1 0 1]
 [0 0 0 0 0]]
105.0
[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 0 1]
 [0 0 0 1 1]]
107.0
[[0 0 0 0 0]
 [1 1 1 0 1]
 [0 0 0 0 0]
 [0 0 0 1 1]]
124.0
[[0 0 0 0 0]
 [0 1 0 0 1]
 [1 0 1 1 1]
 [0 0 0 0 0]]
126.0
[[0 0 0 0 0]
 [1 1 0 0 1]
 [0 0 0 0 0]
 [0 0 1 1 1]]
126.0
[[0 0 0 0 0]
 [1 1 0 0 1]
 [0 0 1 1 1]
 [0 0 0 0 0]]
126.0
[[1 1 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 1 1]]
126.0
[[1 1 0 

## Improved Linear Solution

### Class Solution

In [ ]:
class Solution:
  def __init__(self, vertices: int, p: list, c_mat):
    self.v = vertices
    self.p = p
    self.c_mat = c_mat
    # self.s_mat = np.full((vertices, vertices), 0, dtype=int)
    self.s_vet = []

    # col iterator
    self.i = 0

    # solution cost
    self.c = 0.0

    # possible solution
    self.impossible = False

    self.nancount = 0

  # exec sol step
  def sol_step(self):
    if self.i < self.v:
      min_cost_serv = float("inf")
      min_cost_serv_ind = None
      for serv in self.p:

        # if cost not def continue
        if np.isnan(self.c_mat[serv][self.i]):
          continue

        # update cost min
        if self.c_mat[serv][self.i] < min_cost_serv:
          min_cost_serv = self.c_mat[serv][self.i]
          min_cost_serv_ind = serv

      # if not find edge sol, is impossible
      if min_cost_serv_ind is None :
        self.impossible = True;
        self.c = float("inf")
        self.i = self.v

      # update solution
      else:
        # add sol into v_mat
        self.s_vet.append(min_cost_serv_ind)
        # iterate col
        self.i = self.i + 1
        # update cost
        self.c = self.c + min_cost_serv

  def solved(self):
    if self.i < self.v:
      return False
    else:
      return True

  def __lt__(self, s):
    return self.c < s.c

  def __le__(self, s):
    return self.c <= s.c

  def __eq__(self, s):
    return self.c == s.c

  def __gt__(self, s):
    return self.c > s.c

  def __ge__(self, s):
    return self.c >= s.c



### Solver

In [ ]:
def solver(vertices, edges, p, cost_mat):
  solutions = []

  # create solutions instances
  comb = combinations(range(vertices), p)
  for c in list(comb):
    s = Solution(vertices, c, cost_mat)
    solutions.append(s)

  # resolve all solutions
  for s in solutions:
    while not s.solved():
      s.sol_step()
  return solutions








### Execute Solution

In [ ]:
h = []

for pmed in synthetic_pmeds:
  data = get_dataset(pmed)

  start_time =  datetime.datetime.now()
  solutions = solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])
  end_time =  datetime.datetime.now()

  solutions.sort()

  h.append({
      "file": pmed,
      "start_time": start_time,
      "end_time": end_time,
      "min_cost": solutions[0].c,
      "s_vet": solutions[0].s_vet
  })
  print(h)

print(h)

[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 10, 15, 44, 29, 317428), 'end_time': datetime.datetime(2023, 7, 10, 15, 44, 29, 320055), 'min_cost': 153.0, 's_vet': [0, 3, 3, 3, 0, 3, 3, 3, 0, 3]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 10, 15, 44, 29, 317428), 'end_time': datetime.datetime(2023, 7, 10, 15, 44, 29, 320055), 'min_cost': 153.0, 's_vet': [0, 3, 3, 3, 0, 3, 3, 3, 0, 3]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 10, 15, 44, 29, 321443), 'end_time': datetime.datetime(2023, 7, 10, 15, 44, 29, 350523), 'min_cost': 349.0, 's_vet': [19, 11, 19, 11, 19, 11, 11, 11, 19, 19, 11, 11, 11, 19, 11, 19, 19, 11, 19, 19]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 10, 15, 44, 29, 317428), 'end_time': datetime.datetime(2023, 7, 10, 15, 44, 29, 320055), 'min_cost': 153.0, 's_vet': [0, 3, 3, 3, 0, 3, 3, 3, 0, 3]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 10, 15, 44, 

In [ ]:
h_df = pd.DataFrame(h)
print(h_df)
h_df.to_csv("linear_sol.csv")

## Linear Solution with Heuristics

### Solver

In [ ]:
def heuristic_solver(vertices, edges, p, cost_mat):
  solutions = []

  # create solutions instances
  comb = combinations(range(vertices), p)
  for c in list(comb):
    s = Solution(vertices, c, cost_mat)
    solutions.append(s)

  # get first of priority queue
  s = solutions[0]
  while not s.solved() and not s.impossible:

    # sol step first of heap
    s.sol_step()

    if s.impossible:
      heapq.heappop(solutions)

    # heapify heap
    heapq.heapify(solutions)
    # get most promising solution
    s = solutions[0]

  return solutions

In [ ]:
h = []

for pmed in synthetic_pmeds:
  data = get_dataset(pmed)

  start_time =  datetime.datetime.now()
  solutions = heuristic_solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])
  end_time =  datetime.datetime.now()

  solutions.sort()

  h.append({
      "file": pmed,
      "start_time": start_time,
      "end_time": end_time,
      "min_cost": solutions[0].c,
      "s_vet": solutions[0].s_vet
  })
  print(h)

print(h)

In [ ]:
h_df = pd.DataFrame(h)
print(h_df)
h_df.to_csv("heuristic_old_sol.csv")

## Myopic Solution

### Solver

In [ ]:
def heuristic_myopic_solver(vertices, edges, p, cost_mat):
  # solutions = []

  # create solutions instances
  solution_candidate = []
  s = None
  while len(solution_candidate) < p:
    s_list = solution_candidate.copy()
    s_list_temp = solution_candidate.copy()
    s_list_temp.append(-1)
    s_cost = float("inf")
    s_temp = None

    for i in range(vertices):
      if i not in s_list:
        s_list_temp[len(solution_candidate)] = i
        s_temp = Solution(vertices, s_list_temp, cost_mat)

        while not s_temp.solved():
          s_temp.sol_step()

        if s_cost > s_temp.c:
          # print(s_temp.c)
          s_list = s_list_temp
          s_cost = s_temp.c
          s = s_temp

    solution_candidate = s_list
  return s, solution_candidate

In [ ]:
h = []

for pmed in synthetic_pmeds:
  data = get_dataset(pmed)

  start_time =  datetime.datetime.now()
  solutions = heuristic_myopic_solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])
  end_time =  datetime.datetime.now()

  # solutions.sort()

  h.append({
      "file": pmed,
      "start_time": start_time,
      "end_time": end_time,
      "min_cost": solutions[0].c,
      "s_vet": solutions[0].s_vet
  })
  print(h)

print(h)

[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 10, 19, 55, 35, 868846), 'end_time': datetime.datetime(2023, 7, 10, 19, 55, 35, 869836), 'min_cost': 215.0, 's_vet': [3, 3, 3, 3, 3, 3, 3, 3, 9, 9]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 10, 19, 55, 35, 868846), 'end_time': datetime.datetime(2023, 7, 10, 19, 55, 35, 869836), 'min_cost': 215.0, 's_vet': [3, 3, 3, 3, 3, 3, 3, 3, 9, 9]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 10, 19, 55, 35, 871403), 'end_time': datetime.datetime(2023, 7, 10, 19, 55, 35, 874908), 'min_cost': 349.0, 's_vet': [19, 11, 19, 11, 19, 11, 11, 11, 19, 19, 11, 11, 11, 19, 11, 19, 19, 11, 19, 19]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 10, 19, 55, 35, 868846), 'end_time': datetime.datetime(2023, 7, 10, 19, 55, 35, 869836), 'min_cost': 215.0, 's_vet': [3, 3, 3, 3, 3, 3, 3, 3, 9, 9]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 10, 19, 55, 

In [ ]:
h_df = pd.DataFrame(h)
print(h_df)
h_df.to_csv("heuristic_myopic_sol.csv")

## Exchange Solution

### Solver

In [ ]:
def heuristic_exchange_solver(vertices, edges, p, cost_mat, sol_init = None):

  # def sol init
  if sol_init is None:
    solution_candidate = random.choices(range(vertices), k=p)
  else:
    solution_candidate = sol_init

  # create sol init instance
  s = Solution(vertices, solution_candidate, cost_mat)
  while not s.solved():
    s.sol_step()


  for i in range(p):
    for j in range(vertices):

      solution_temp = solution_candidate.copy()
      if j in solution_candidate:
        continue

      solution_temp[i] = j
      s_temp = Solution(vertices, solution_temp, cost_mat)

      while not s_temp.solved():
        s_temp.sol_step()

      if s_temp.c < s.c:
        solution_candidate = solution_temp
        s = s_temp
  return s, solution_candidate

In [ ]:
h = []

for pmed in synthetic_pmeds:
  data = get_dataset(pmed)

  start_time =  datetime.datetime.now()
  solutions = heuristic_exchange_solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])
  end_time =  datetime.datetime.now()


  h.append({
      "file": pmed,
      "start_time": start_time,
      "end_time": end_time,
      "min_cost": solutions[0].c,
      "s_vet": solutions[0].s_vet
  })
  print(h)

print(h)

[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 1, 17, 55, 347463), 'end_time': datetime.datetime(2023, 7, 11, 1, 17, 55, 348607), 'min_cost': 153.0, 's_vet': [0, 3, 3, 3, 0, 3, 3, 3, 0, 3]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 1, 17, 55, 347463), 'end_time': datetime.datetime(2023, 7, 11, 1, 17, 55, 348607), 'min_cost': 153.0, 's_vet': [0, 3, 3, 3, 0, 3, 3, 3, 0, 3]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 1, 17, 55, 349343), 'end_time': datetime.datetime(2023, 7, 11, 1, 17, 55, 353769), 'min_cost': 349.0, 's_vet': [19, 11, 19, 11, 19, 11, 11, 11, 19, 19, 11, 11, 11, 19, 11, 19, 19, 11, 19, 19]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 1, 17, 55, 347463), 'end_time': datetime.datetime(2023, 7, 11, 1, 17, 55, 348607), 'min_cost': 153.0, 's_vet': [0, 3, 3, 3, 0, 3, 3, 3, 0, 3]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 1, 17, 55, 34934

In [ ]:
h_df = pd.DataFrame(h)
print(h_df)
h_df.to_csv("heuristic_exchange_sol.csv")

## Exchange + Myopic Solution

### Solver

In [ ]:
def heuristic_exchange_myopic_solver(vertices, edges, p, cost_mat):
  # solutions = []

  # def sol init
  s_ini, sol_init  = heuristic_myopic_solver(vertices, edges, p, cost_mat)

  # def sol final
  s_final, sol_final = heuristic_exchange_solver(vertices, edges, p, cost_mat, sol_init)

  return s_final, sol_final

In [ ]:
h = []

for pmed in synthetic_pmeds:
  data = get_dataset(pmed)

  start_time =  datetime.datetime.now()
  solutions = heuristic_exchange_myopic_solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])
  end_time =  datetime.datetime.now()


  h.append({
      "file": pmed,
      "start_time": start_time,
      "end_time": end_time,
      "min_cost": solutions[0].c,
      "s_vet": solutions[0].s_vet
  })
  print(h)

print(h)

[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 1, 45, 48, 362864), 'end_time': datetime.datetime(2023, 7, 11, 1, 45, 48, 366230), 'min_cost': 153.0, 's_vet': [0, 3, 3, 3, 0, 3, 3, 3, 0, 3]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 1, 45, 48, 362864), 'end_time': datetime.datetime(2023, 7, 11, 1, 45, 48, 366230), 'min_cost': 153.0, 's_vet': [0, 3, 3, 3, 0, 3, 3, 3, 0, 3]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 1, 45, 48, 367636), 'end_time': datetime.datetime(2023, 7, 11, 1, 45, 48, 375573), 'min_cost': 471.0, 's_vet': [6, 17, 6, 6, 17, 6, 6, 17, 6, 17, 6, 17, 6, 17, 17, 17, 17, 6, 6, 17]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 1, 45, 48, 362864), 'end_time': datetime.datetime(2023, 7, 11, 1, 45, 48, 366230), 'min_cost': 153.0, 's_vet': [0, 3, 3, 3, 0, 3, 3, 3, 0, 3]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 1, 45, 48, 367636), 'end_t

In [ ]:
h_df = pd.DataFrame(h)
print(h_df)
h_df.to_csv("heuristic_exchange_myopic_sol.csv")

## Myopic Solution with Exchange Correction

### Solver

In [ ]:
def exchange_correction(vertices, edges, p, cost_mat, sol_candidate):
  # create sol init instance
  s = Solution(vertices, sol_candidate, cost_mat)
  while not s.solved():
    s.sol_step()

  for i in range(len(sol_candidate) - 1, -1, -1):
    for j in range(vertices):

      solution_temp = sol_candidate.copy()
      if j in sol_candidate:
        continue

      solution_temp[i] = j
      s_temp = Solution(vertices, solution_temp, cost_mat)

      while not s_temp.solved():
        s_temp.sol_step()

      if s_temp.c < s.c:
        sol_candidate = solution_temp
        s = s_temp
  return s, sol_candidate


def heuristic_myopic_with_exchange_corr_solver(vertices, edges, p, cost_mat):

  # create solutions instances
  solution_candidate = []
  s = None
  while len(solution_candidate) < p:
    s_list = solution_candidate.copy()
    s_list_temp = solution_candidate.copy()
    s_list_temp.append(-1)
    s_cost = float("inf")
    s_temp = None

    # myopic add
    for i in range(vertices):
      if i not in s_list:
        s_list_temp[len(solution_candidate)] = i
        s_temp = Solution(vertices, s_list_temp, cost_mat)

        while not s_temp.solved():
          s_temp.sol_step()

        if s_cost > s_temp.c:
          s_list = s_list_temp
          s_cost = s_temp.c
          s = s_temp

    solution_candidate = s_list

    # exchange correction
    s, solution_candidate = exchange_correction(vertices, edges, p, cost_mat, solution_candidate)
  return s, solution_candidate

In [ ]:
h = []

for pmed in synthetic_pmeds:
  data = get_dataset(pmed)

  start_time =  datetime.datetime.now()
  solutions = heuristic_myopic_with_exchange_corr_solver(data["vertices"], data["edges"], data["p"], data["cost_mat"])
  end_time =  datetime.datetime.now()

  h.append({
      "file": pmed,
      "start_time": start_time,
      "end_time": end_time,
      "min_cost": solutions[0].c,
      "s_vet": solutions[0].s_vet
  })
  print(h)

print(h)

[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 2, 1, 54, 269108), 'end_time': datetime.datetime(2023, 7, 11, 2, 1, 54, 272326), 'min_cost': 153.0, 's_vet': [0, 3, 3, 3, 0, 3, 3, 3, 0, 3]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 2, 1, 54, 269108), 'end_time': datetime.datetime(2023, 7, 11, 2, 1, 54, 272326), 'min_cost': 153.0, 's_vet': [0, 3, 3, 3, 0, 3, 3, 3, 0, 3]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 2, 1, 54, 274109), 'end_time': datetime.datetime(2023, 7, 11, 2, 1, 54, 284184), 'min_cost': 349.0, 's_vet': [19, 11, 19, 11, 19, 11, 11, 11, 19, 19, 11, 11, 11, 19, 11, 19, 19, 11, 19, 19]}]
[{'file': 'syntpmed1.txt', 'start_time': datetime.datetime(2023, 7, 11, 2, 1, 54, 269108), 'end_time': datetime.datetime(2023, 7, 11, 2, 1, 54, 272326), 'min_cost': 153.0, 's_vet': [0, 3, 3, 3, 0, 3, 3, 3, 0, 3]}, {'file': 'syntpmed2.txt', 'start_time': datetime.datetime(2023, 7, 11, 2, 1, 54, 274109), 'end_

In [ ]:
h_df = pd.DataFrame(h)
print(h_df)
h_df.to_csv("heuristic_myopic_with_exchange_corr_sol.csv")

## Results